# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1061, 683)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QPushButton,QComboBox{\n"
"    min-height:22px    \n"
"}\n"
"\n"
"QSpinBox, QDoubleSpinBox{\n"
"    min-height:20px    \n"
"}\n"
"")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setGeometry(QtCore.QRect(5, 5, 1031, 596))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.toolBox = QtWidgets.QToolBox(self.splitter)
        self.toolBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 400, 506))
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 392, 498))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btnTitleSetText = QtWidgets.QPushButton(self.groupBox)
        self.btnTitleSetText.setObjectName("btnTitleSetText")
        self.gridLayout_9.addWidget(self.btnTitleSetText, 0, 0, 1, 1)
        self.editTitle = QtWidgets.QLineEdit(self.groupBox)
        self.editTitle.setObjectName("editTitle")
        self.gridLayout_9.addWidget(self.editTitle, 0, 1, 1, 1)
        self.btnTitleColor = QtWidgets.QPushButton(self.groupBox)
        self.btnTitleColor.setObjectName("btnTitleColor")
        self.gridLayout_9.addWidget(self.btnTitleColor, 1, 0, 1, 1)
        self.btnTitleFont = QtWidgets.QPushButton(self.groupBox)
        self.btnTitleFont.setObjectName("btnTitleFont")
        self.gridLayout_9.addWidget(self.btnTitleFont, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_Legend = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_Legend.setCheckable(True)
        self.groupBox_Legend.setChecked(True)
        self.groupBox_Legend.setObjectName("groupBox_Legend")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_Legend)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_Legend)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_7.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_Legend)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_7.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_Legend)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_7.addWidget(self.radioButton_3, 1, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_Legend)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_7.addWidget(self.radioButton_4, 1, 1, 1, 1)
        self.btnLegendlabelColor = QtWidgets.QPushButton(self.groupBox_Legend)
        self.btnLegendlabelColor.setObjectName("btnLegendlabelColor")
        self.gridLayout_7.addWidget(self.btnLegendlabelColor, 2, 0, 1, 1)
        self.btnLegendFont = QtWidgets.QPushButton(self.groupBox_Legend)
        self.btnLegendFont.setObjectName("btnLegendFont")
        self.gridLayout_7.addWidget(self.btnLegendFont, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_Legend)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinMarginLeft = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinMarginLeft.setMinimum(10)
        self.spinMarginLeft.setMaximum(500)
        self.spinMarginLeft.setObjectName("spinMarginLeft")
        self.gridLayout.addWidget(self.spinMarginLeft, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinMarginRight = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinMarginRight.setMinimum(10)
        self.spinMarginRight.setMaximum(500)
        self.spinMarginRight.setObjectName("spinMarginRight")
        self.gridLayout.addWidget(self.spinMarginRight, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinMarginTop = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinMarginTop.setMinimum(10)
        self.spinMarginTop.setMaximum(500)
        self.spinMarginTop.setObjectName("spinMarginTop")
        self.gridLayout.addWidget(self.spinMarginTop, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinMarginBottom = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinMarginBottom.setMinimum(10)
        self.spinMarginBottom.setMaximum(500)
        self.spinMarginBottom.setObjectName("spinMarginBottom")
        self.gridLayout.addWidget(self.spinMarginBottom, 3, 1, 1, 1)
        self.btnSetMargin = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSetMargin.setObjectName("btnSetMargin")
        self.gridLayout.addWidget(self.btnSetMargin, 4, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_15 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_6 = QtWidgets.QLabel(self.groupBox_15)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_10.addWidget(self.label_6, 0, 0, 1, 1)
        self.comboAnimation = QtWidgets.QComboBox(self.groupBox_15)
        self.comboAnimation.setObjectName("comboAnimation")
        self.comboAnimation.addItem("")
        self.comboAnimation.addItem("")
        self.comboAnimation.addItem("")
        self.comboAnimation.addItem("")
        self.gridLayout_10.addWidget(self.comboAnimation, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_15)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 1, 0, 1, 1)
        self.comboTheme = QtWidgets.QComboBox(self.groupBox_15)
        self.comboTheme.setObjectName("comboTheme")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.gridLayout_10.addWidget(self.comboTheme, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_15)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 400, 506))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_10.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_10.setSpacing(3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 392, 498))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_12 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioSeries0 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioSeries0.setChecked(True)
        self.radioSeries0.setObjectName("radioSeries0")
        self.horizontalLayout_3.addWidget(self.radioSeries0)
        self.radioSeries1 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioSeries1.setObjectName("radioSeries1")
        self.horizontalLayout_3.addWidget(self.radioSeries1)
        self.verticalLayout_9.addWidget(self.groupBox_12)
        self.groupBox_Series = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_Series.setCheckable(True)
        self.groupBox_Series.setChecked(True)
        self.groupBox_Series.setObjectName("groupBox_Series")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_Series)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnSeriesName = QtWidgets.QPushButton(self.groupBox_Series)
        self.btnSeriesName.setObjectName("btnSeriesName")
        self.gridLayout_3.addWidget(self.btnSeriesName, 0, 0, 1, 1)
        self.editSeriesName = QtWidgets.QLineEdit(self.groupBox_Series)
        self.editSeriesName.setObjectName("editSeriesName")
        self.gridLayout_3.addWidget(self.editSeriesName, 0, 1, 1, 1)
        self.btnSeriesColor = QtWidgets.QPushButton(self.groupBox_Series)
        self.btnSeriesColor.setObjectName("btnSeriesColor")
        self.gridLayout_3.addWidget(self.btnSeriesColor, 1, 0, 1, 1)
        self.btnSeriesPen = QtWidgets.QPushButton(self.groupBox_Series)
        self.btnSeriesPen.setObjectName("btnSeriesPen")
        self.gridLayout_3.addWidget(self.btnSeriesPen, 1, 1, 1, 1)
        self.chkkBoxUseOpenGL = QtWidgets.QCheckBox(self.groupBox_Series)
        self.chkkBoxUseOpenGL.setObjectName("chkkBoxUseOpenGL")
        self.gridLayout_3.addWidget(self.chkkBoxUseOpenGL, 2, 0, 1, 1)
        self.chkBoxPointVisible = QtWidgets.QCheckBox(self.groupBox_Series)
        self.chkBoxPointVisible.setObjectName("chkBoxPointVisible")
        self.gridLayout_3.addWidget(self.chkBoxPointVisible, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_Series)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.sliderOpacity = QtWidgets.QSlider(self.groupBox_Series)
        self.sliderOpacity.setMaximum(10)
        self.sliderOpacity.setPageStep(2)
        self.sliderOpacity.setProperty("value", 10)
        self.sliderOpacity.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOpacity.setObjectName("sliderOpacity")
        self.gridLayout_3.addWidget(self.sliderOpacity, 3, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_Series)
        self.groupBox_PointLabel = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_PointLabel.setCheckable(True)
        self.groupBox_PointLabel.setChecked(False)
        self.groupBox_PointLabel.setObjectName("groupBox_PointLabel")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_PointLabel)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnSeriesLabColor = QtWidgets.QPushButton(self.groupBox_PointLabel)
        self.btnSeriesLabColor.setObjectName("btnSeriesLabColor")
        self.horizontalLayout_4.addWidget(self.btnSeriesLabColor)
        self.btnSeriesLabFont = QtWidgets.QPushButton(self.groupBox_PointLabel)
        self.btnSeriesLabFont.setObjectName("btnSeriesLabFont")
        self.horizontalLayout_4.addWidget(self.btnSeriesLabFont)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_PointLabel)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioSeriesLabFormat0 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioSeriesLabFormat0.setChecked(True)
        self.radioSeriesLabFormat0.setObjectName("radioSeriesLabFormat0")
        self.verticalLayout_6.addWidget(self.radioSeriesLabFormat0)
        self.radioSeriesLabFormat1 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioSeriesLabFormat1.setObjectName("radioSeriesLabFormat1")
        self.verticalLayout_6.addWidget(self.radioSeriesLabFormat1)
        self.verticalLayout_7.addWidget(self.groupBox_14)
        self.verticalLayout_9.addWidget(self.groupBox_PointLabel)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_10.addWidget(self.scrollArea_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/dis3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_2, icon1, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 400, 506))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.page_3)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 375, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_SelectAxis = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_SelectAxis.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_SelectAxis.setObjectName("groupBox_SelectAxis")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_SelectAxis)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioAxisX = QtWidgets.QRadioButton(self.groupBox_SelectAxis)
        self.radioAxisX.setChecked(True)
        self.radioAxisX.setObjectName("radioAxisX")
        self.horizontalLayout_2.addWidget(self.radioAxisX)
        self.radioAxisY = QtWidgets.QRadioButton(self.groupBox_SelectAxis)
        self.radioAxisY.setChecked(False)
        self.radioAxisY.setObjectName("radioAxisY")
        self.horizontalLayout_2.addWidget(self.radioAxisY)
        self.verticalLayout_8.addWidget(self.groupBox_SelectAxis)
        self.groupBox_Axis = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_Axis.setFlat(True)
        self.groupBox_Axis.setCheckable(True)
        self.groupBox_Axis.setObjectName("groupBox_Axis")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Axis)
        self.verticalLayout_2.setContentsMargins(0, 11, 0, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.groupBox_Axis)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.spinAxisMin = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinAxisMin.setMinimum(-1000.0)
        self.spinAxisMin.setMaximum(1000.0)
        self.spinAxisMin.setObjectName("spinAxisMin")
        self.gridLayout_4.addWidget(self.spinAxisMin, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.spinAxisMax = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinAxisMax.setMinimum(-1000.0)
        self.spinAxisMax.setMaximum(1000.0)
        self.spinAxisMax.setProperty("value", 10.0)
        self.spinAxisMax.setObjectName("spinAxisMax")
        self.gridLayout_4.addWidget(self.spinAxisMax, 1, 1, 1, 1)
        self.btnSetAxisRange = QtWidgets.QPushButton(self.frame)
        self.btnSetAxisRange.setObjectName("btnSetAxisRange")
        self.gridLayout_4.addWidget(self.btnSetAxisRange, 1, 2, 1, 1)
        self.chkBoxAxisReverse = QtWidgets.QCheckBox(self.frame)
        self.chkBoxAxisReverse.setObjectName("chkBoxAxisReverse")
        self.gridLayout_4.addWidget(self.chkBoxAxisReverse, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.groupBox_AxisTitle = QtWidgets.QGroupBox(self.groupBox_Axis)
        self.groupBox_AxisTitle.setCheckable(True)
        self.groupBox_AxisTitle.setObjectName("groupBox_AxisTitle")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_AxisTitle)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnAxisSetTitle = QtWidgets.QPushButton(self.groupBox_AxisTitle)
        self.btnAxisSetTitle.setObjectName("btnAxisSetTitle")
        self.gridLayout_2.addWidget(self.btnAxisSetTitle, 0, 0, 1, 1)
        self.editAxisTitle = QtWidgets.QLineEdit(self.groupBox_AxisTitle)
        self.editAxisTitle.setObjectName("editAxisTitle")
        self.gridLayout_2.addWidget(self.editAxisTitle, 0, 1, 1, 1)
        self.btnAxisTitleColor = QtWidgets.QPushButton(self.groupBox_AxisTitle)
        self.btnAxisTitleColor.setObjectName("btnAxisTitleColor")
        self.gridLayout_2.addWidget(self.btnAxisTitleColor, 1, 0, 1, 1)
        self.btnAxisTitleFont = QtWidgets.QPushButton(self.groupBox_AxisTitle)
        self.btnAxisTitleFont.setObjectName("btnAxisTitleFont")
        self.gridLayout_2.addWidget(self.btnAxisTitleFont, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_AxisTitle)
        self.groupBox_AxisLabel = QtWidgets.QGroupBox(self.groupBox_Axis)
        self.groupBox_AxisLabel.setCheckable(True)
        self.groupBox_AxisLabel.setObjectName("groupBox_AxisLabel")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_AxisLabel)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btnAxisLabelFormat = QtWidgets.QPushButton(self.groupBox_AxisLabel)
        self.btnAxisLabelFormat.setObjectName("btnAxisLabelFormat")
        self.gridLayout_6.addWidget(self.btnAxisLabelFormat, 0, 0, 1, 1)
        self.editAxisLabelFormat = QtWidgets.QLineEdit(self.groupBox_AxisLabel)
        self.editAxisLabelFormat.setObjectName("editAxisLabelFormat")
        self.gridLayout_6.addWidget(self.editAxisLabelFormat, 0, 1, 1, 1)
        self.btnAxisLabelColor = QtWidgets.QPushButton(self.groupBox_AxisLabel)
        self.btnAxisLabelColor.setObjectName("btnAxisLabelColor")
        self.gridLayout_6.addWidget(self.btnAxisLabelColor, 1, 0, 1, 1)
        self.btnAxisLabelFont = QtWidgets.QPushButton(self.groupBox_AxisLabel)
        self.btnAxisLabelFont.setMinimumSize(QtCore.QSize(0, 24))
        self.btnAxisLabelFont.setObjectName("btnAxisLabelFont")
        self.gridLayout_6.addWidget(self.btnAxisLabelFont, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_AxisLabel)
        self.groupBox_Ticks = QtWidgets.QGroupBox(self.groupBox_Axis)
        self.groupBox_Ticks.setCheckable(True)
        self.groupBox_Ticks.setObjectName("groupBox_Ticks")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_Ticks)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox_Ticks)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.spinTickCount = QtWidgets.QSpinBox(self.groupBox_Ticks)
        self.spinTickCount.setMinimum(1)
        self.spinTickCount.setMaximum(1000)
        self.spinTickCount.setProperty("value", 10)
        self.spinTickCount.setObjectName("spinTickCount")
        self.gridLayout_5.addWidget(self.spinTickCount, 0, 1, 1, 1)
        self.btnAxisLinePen = QtWidgets.QPushButton(self.groupBox_Ticks)
        self.btnAxisLinePen.setObjectName("btnAxisLinePen")
        self.gridLayout_5.addWidget(self.btnAxisLinePen, 1, 0, 1, 1)
        self.btnAxisLinePenColor = QtWidgets.QPushButton(self.groupBox_Ticks)
        self.btnAxisLinePenColor.setObjectName("btnAxisLinePenColor")
        self.gridLayout_5.addWidget(self.btnAxisLinePenColor, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_Ticks)
        self.groupBox_GridLine = QtWidgets.QGroupBox(self.groupBox_Axis)
        self.groupBox_GridLine.setCheckable(True)
        self.groupBox_GridLine.setObjectName("groupBox_GridLine")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_GridLine)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnGridLinePen = QtWidgets.QPushButton(self.groupBox_GridLine)
        self.btnGridLinePen.setObjectName("btnGridLinePen")
        self.horizontalLayout_5.addWidget(self.btnGridLinePen)
        self.btnGridLineColor = QtWidgets.QPushButton(self.groupBox_GridLine)
        self.btnGridLineColor.setObjectName("btnGridLineColor")
        self.horizontalLayout_5.addWidget(self.btnGridLineColor)
        self.verticalLayout_2.addWidget(self.groupBox_GridLine)
        self.groupBox_MinorGrid = QtWidgets.QGroupBox(self.groupBox_Axis)
        self.groupBox_MinorGrid.setCheckable(True)
        self.groupBox_MinorGrid.setObjectName("groupBox_MinorGrid")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_MinorGrid)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox_MinorGrid)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 0, 1, 1)
        self.spinMinorTickCount = QtWidgets.QSpinBox(self.groupBox_MinorGrid)
        self.spinMinorTickCount.setProperty("value", 4)
        self.spinMinorTickCount.setObjectName("spinMinorTickCount")
        self.gridLayout_8.addWidget(self.spinMinorTickCount, 0, 1, 1, 1)
        self.btnMinorPen = QtWidgets.QPushButton(self.groupBox_MinorGrid)
        self.btnMinorPen.setObjectName("btnMinorPen")
        self.gridLayout_8.addWidget(self.btnMinorPen, 1, 0, 1, 1)
        self.btnMinorColor = QtWidgets.QPushButton(self.groupBox_MinorGrid)
        self.btnMinorColor.setObjectName("btnMinorColor")
        self.gridLayout_8.addWidget(self.btnMinorColor, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_MinorGrid)
        self.verticalLayout_8.addWidget(self.groupBox_Axis)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/39.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_3, icon2, "")
        self.frame_chart = QtWidgets.QFrame(self.splitter)
        self.frame_chart.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_chart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_chart.setObjectName("frame_chart")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_chart)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chartView = QChartView(self.frame_chart)
        self.chartView.setObjectName("chartView")
        self.verticalLayout.addWidget(self.chartView)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actDraw = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/828.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actDraw.setIcon(icon3)
        self.actDraw.setObjectName("actDraw")
        self.actQuit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actQuit.setIcon(icon4)
        self.actQuit.setObjectName("actQuit")
        self.actZoomIn = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/418.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomIn.setIcon(icon5)
        self.actZoomIn.setObjectName("actZoomIn")
        self.actZoomOut = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/416.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomOut.setIcon(icon6)
        self.actZoomOut.setObjectName("actZoomOut")
        self.actZoomReset = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/414.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomReset.setIcon(icon7)
        self.actZoomReset.setObjectName("actZoomReset")
        self.mainToolBar.addAction(self.actDraw)
        self.mainToolBar.addAction(self.actQuit)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(2)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QChart绘图详细功能"))
        self.groupBox.setTitle(_translate("MainWindow", "标题"))
        self.btnTitleSetText.setToolTip(_translate("MainWindow", "设置标题文字"))
        self.btnTitleSetText.setText(_translate("MainWindow", "设置标题"))
        self.editTitle.setText(_translate("MainWindow", "简单函数曲线"))
        self.btnTitleColor.setText(_translate("MainWindow", "标题文字颜色"))
        self.btnTitleFont.setText(_translate("MainWindow", "标题字体"))
        self.groupBox_Legend.setTitle(_translate("MainWindow", "图例"))
        self.radioButton.setText(_translate("MainWindow", "上方"))
        self.radioButton_2.setText(_translate("MainWindow", "下方"))
        self.radioButton_3.setText(_translate("MainWindow", "左侧"))
        self.radioButton_4.setText(_translate("MainWindow", "右侧"))
        self.btnLegendlabelColor.setText(_translate("MainWindow", "文字颜色"))
        self.btnLegendFont.setText(_translate("MainWindow", "图例字体"))
        self.groupBox_2.setTitle(_translate("MainWindow", "边距"))
        self.label.setText(_translate("MainWindow", "左边距"))
        self.label_2.setText(_translate("MainWindow", "右边距"))
        self.label_3.setText(_translate("MainWindow", "上边距"))
        self.label_4.setText(_translate("MainWindow", "下边距"))
        self.btnSetMargin.setText(_translate("MainWindow", "设置边距"))
        self.groupBox_15.setTitle(_translate("MainWindow", "动画效果"))
        self.label_6.setText(_translate("MainWindow", "动画效果"))
        self.comboAnimation.setItemText(0, _translate("MainWindow", "NoAnimation"))
        self.comboAnimation.setItemText(1, _translate("MainWindow", "GridAxisAnimations"))
        self.comboAnimation.setItemText(2, _translate("MainWindow", "SeriesAnimations"))
        self.comboAnimation.setItemText(3, _translate("MainWindow", "AllAnimations"))
        self.label_8.setText(_translate("MainWindow", "主  题"))
        self.comboTheme.setItemText(0, _translate("MainWindow", "Light"))
        self.comboTheme.setItemText(1, _translate("MainWindow", "BlueCerulean"))
        self.comboTheme.setItemText(2, _translate("MainWindow", "Dark"))
        self.comboTheme.setItemText(3, _translate("MainWindow", "BrownSand"))
        self.comboTheme.setItemText(4, _translate("MainWindow", "BlueNcs"))
        self.comboTheme.setItemText(5, _translate("MainWindow", "HighContrast"))
        self.comboTheme.setItemText(6, _translate("MainWindow", "BlueIcy"))
        self.comboTheme.setItemText(7, _translate("MainWindow", "Qt"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "图表设置"))
        self.groupBox_12.setTitle(_translate("MainWindow", "选择操作序列"))
        self.radioSeries0.setText(_translate("MainWindow", "Sin曲线"))
        self.radioSeries1.setText(_translate("MainWindow", "Cos曲线"))
        self.groupBox_Series.setTitle(_translate("MainWindow", "序列曲线"))
        self.btnSeriesName.setText(_translate("MainWindow", "序列名称"))
        self.editSeriesName.setText(_translate("MainWindow", "Sin曲线"))
        self.btnSeriesColor.setText(_translate("MainWindow", "曲线颜色"))
        self.btnSeriesPen.setText(_translate("MainWindow", "曲线Pen"))
        self.chkkBoxUseOpenGL.setToolTip(_translate("MainWindow", "使用openGL后不能设置线型，不能显示数据点"))
        self.chkkBoxUseOpenGL.setText(_translate("MainWindow", "使用openGL"))
        self.chkBoxPointVisible.setText(_translate("MainWindow", "数据点可见"))
        self.label_5.setText(_translate("MainWindow", "透明度"))
        self.groupBox_PointLabel.setTitle(_translate("MainWindow", "数据点标签"))
        self.btnSeriesLabColor.setText(_translate("MainWindow", "标签颜色"))
        self.btnSeriesLabFont.setText(_translate("MainWindow", "标签字体"))
        self.groupBox_14.setTitle(_translate("MainWindow", "标签格式"))
        self.radioSeriesLabFormat0.setText(_translate("MainWindow", "@yPoint"))
        self.radioSeriesLabFormat1.setText(_translate("MainWindow", "(@xPoint, @yPoint)"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "曲线设置"))
        self.groupBox_SelectAxis.setTitle(_translate("MainWindow", "选择操作的坐标轴对象"))
        self.radioAxisX.setText(_translate("MainWindow", "X轴"))
        self.radioAxisY.setText(_translate("MainWindow", "Y轴"))
        self.groupBox_Axis.setTitle(_translate("MainWindow", "坐标轴(setVisible())"))
        self.label_7.setText(_translate("MainWindow", "最小值"))
        self.label_11.setText(_translate("MainWindow", "最大值"))
        self.btnSetAxisRange.setText(_translate("MainWindow", "设置坐标范围"))
        self.chkBoxAxisReverse.setText(_translate("MainWindow", "坐标反向"))
        self.groupBox_AxisTitle.setTitle(_translate("MainWindow", "轴标题(setTitleVisible())"))
        self.btnAxisSetTitle.setText(_translate("MainWindow", "设置轴标题"))
        self.editAxisTitle.setText(_translate("MainWindow", "time(secs)"))
        self.btnAxisTitleColor.setText(_translate("MainWindow", "文字颜色"))
        self.btnAxisTitleFont.setText(_translate("MainWindow", "设置字体"))
        self.groupBox_AxisLabel.setTitle(_translate("MainWindow", "轴刻度标签(setLabelsVisible())"))
        self.btnAxisLabelFormat.setText(_translate("MainWindow", "设置标签格式"))
        self.editAxisLabelFormat.setText(_translate("MainWindow", "%.1f"))
        self.btnAxisLabelColor.setText(_translate("MainWindow", "文字颜色"))
        self.btnAxisLabelFont.setText(_translate("MainWindow", "设置字体"))
        self.groupBox_Ticks.setTitle(_translate("MainWindow", "轴线和主刻度(setLineVisible())"))
        self.label_9.setText(_translate("MainWindow", "Tick个数"))
        self.btnAxisLinePen.setText(_translate("MainWindow", "线条Pen"))
        self.btnAxisLinePenColor.setText(_translate("MainWindow", "线条颜色"))
        self.groupBox_GridLine.setTitle(_translate("MainWindow", "主网格线(setGridLineVisible())"))
        self.btnGridLinePen.setText(_translate("MainWindow", "线条Pen"))
        self.btnGridLineColor.setText(_translate("MainWindow", "线条颜色"))
        self.groupBox_MinorGrid.setTitle(_translate("MainWindow", "次网格线(setMinorGridLineVisible())"))
        self.label_10.setText(_translate("MainWindow", "MinorTick个数"))
        self.btnMinorPen.setText(_translate("MainWindow", "线条Pen"))
        self.btnMinorColor.setText(_translate("MainWindow", "线条颜色"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "坐标轴设置"))
        self.actDraw.setText(_translate("MainWindow", "刷新绘图"))
        self.actDraw.setToolTip(_translate("MainWindow", "刷新绘图"))
        self.actQuit.setText(_translate("MainWindow", "退出"))
        self.actQuit.setToolTip(_translate("MainWindow", "退出"))
        self.actZoomIn.setText(_translate("MainWindow", "放大"))
        self.actZoomIn.setToolTip(_translate("MainWindow", "放大"))
        self.actZoomOut.setText(_translate("MainWindow", "缩小"))
        self.actZoomOut.setToolTip(_translate("MainWindow", "缩小"))
        self.actZoomReset.setText(_translate("MainWindow", "原始大小"))
        self.actZoomReset.setToolTip(_translate("MainWindow", "还原为原始大小"))

from PyQt5.QtChart import QChartView
import res_rc
