# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(876, 513)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitterMain = QtWidgets.QSplitter(self.centralWidget)
        self.splitterMain.setOrientation(QtCore.Qt.Horizontal)
        self.splitterMain.setObjectName("splitterMain")
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitterMain)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeView = QtWidgets.QTreeView(self.groupBox_3)
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_3.addWidget(self.treeView)
        self.splitter = QtWidgets.QSplitter(self.splitterMain)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setFlow(QtWidgets.QListView.TopToBottom)
        self.listView.setProperty("isWrapping", True)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtWidgets.QTableView(self.groupBox_2)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setShowGrid(True)
        self.tableView.setGridStyle(QtCore.Qt.DotLine)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.verticalLayout_5.addWidget(self.splitterMain)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 75))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setContentsMargins(11, 5, 11, 2)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LabFileName = QtWidgets.QLabel(self.groupBox_4)
        self.LabFileName.setObjectName("LabFileName")
        self.horizontalLayout.addWidget(self.LabFileName)
        self.LabFileSize = QtWidgets.QLabel(self.groupBox_4)
        self.LabFileSize.setObjectName("LabFileSize")
        self.horizontalLayout.addWidget(self.LabFileSize)
        self.LabType = QtWidgets.QLabel(self.groupBox_4)
        self.LabType.setObjectName("LabType")
        self.horizontalLayout.addWidget(self.LabType)
        self.chkBox_IsDir = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkBox_IsDir.setObjectName("chkBox_IsDir")
        self.horizontalLayout.addWidget(self.chkBox_IsDir)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.groupBox_4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.LabPath = QtWidgets.QLabel(self.groupBox_4)
        self.LabPath.setObjectName("LabPath")
        self.verticalLayout_4.addWidget(self.LabPath)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo4_1, 文件系统Model/View"))
        self.groupBox_3.setTitle(_translate("MainWindow", "TreeView"))
        self.groupBox.setTitle(_translate("MainWindow", "ListView"))
        self.groupBox_2.setTitle(_translate("MainWindow", "TableView"))
        self.LabFileName.setText(_translate("MainWindow", "文件名："))
        self.LabFileSize.setText(_translate("MainWindow", "文件大小："))
        self.LabType.setText(_translate("MainWindow", "节点类型："))
        self.chkBox_IsDir.setText(_translate("MainWindow", "节点是目录"))
        self.LabPath.setText(_translate("MainWindow", "路径名："))

