# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 570)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.toolBox = QtWidgets.QToolBox(self.centralWidget)
        self.toolBox.setGeometry(QtCore.QRect(5, 5, 356, 551))
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setObjectName("toolBox")
        self.page_Figure = QtWidgets.QWidget()
        self.page_Figure.setGeometry(QtCore.QRect(0, 0, 356, 401))
        self.page_Figure.setObjectName("page_Figure")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_Figure)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_Figure)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 348, 393))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_suptitle = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_suptitle.setCheckable(True)
        self.groupBox_suptitle.setObjectName("groupBox_suptitle")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_suptitle)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnFig_Title = QtWidgets.QPushButton(self.groupBox_suptitle)
        self.btnFig_Title.setObjectName("btnFig_Title")
        self.horizontalLayout.addWidget(self.btnFig_Title)
        self.editFig_Title = QtWidgets.QLineEdit(self.groupBox_suptitle)
        self.editFig_Title.setObjectName("editFig_Title")
        self.horizontalLayout.addWidget(self.editFig_Title)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.groupBox_suptitle)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.spinFig_Fontsize = QtWidgets.QSpinBox(self.groupBox_suptitle)
        self.spinFig_Fontsize.setMinimum(5)
        self.spinFig_Fontsize.setMaximum(100)
        self.spinFig_Fontsize.setProperty("value", 16)
        self.spinFig_Fontsize.setObjectName("spinFig_Fontsize")
        self.horizontalLayout_6.addWidget(self.spinFig_Fontsize)
        self.chkBoxFig_Bold = QtWidgets.QCheckBox(self.groupBox_suptitle)
        self.chkBoxFig_Bold.setChecked(True)
        self.chkBoxFig_Bold.setObjectName("chkBoxFig_Bold")
        self.horizontalLayout_6.addWidget(self.chkBoxFig_Bold)
        self.chkBoxFig_Italic = QtWidgets.QCheckBox(self.groupBox_suptitle)
        self.chkBoxFig_Italic.setObjectName("chkBoxFig_Italic")
        self.horizontalLayout_6.addWidget(self.chkBoxFig_Italic)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnFig_TitleColor = QtWidgets.QPushButton(self.groupBox_suptitle)
        self.btnFig_TitleColor.setObjectName("btnFig_TitleColor")
        self.horizontalLayout_7.addWidget(self.btnFig_TitleColor)
        self.btnFig_TitleBackColor = QtWidgets.QPushButton(self.groupBox_suptitle)
        self.btnFig_TitleBackColor.setObjectName("btnFig_TitleBackColor")
        self.horizontalLayout_7.addWidget(self.btnFig_TitleBackColor)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_11.addWidget(self.groupBox_suptitle)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setHorizontalSpacing(6)
        self.gridLayout_7.setVerticalSpacing(9)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.chkBoxFig_FrameOn = QtWidgets.QCheckBox(self.groupBox)
        self.chkBoxFig_FrameOn.setChecked(True)
        self.chkBoxFig_FrameOn.setObjectName("chkBoxFig_FrameOn")
        self.gridLayout_7.addWidget(self.chkBoxFig_FrameOn, 0, 0, 1, 1)
        self.btnFig_FaceColor = QtWidgets.QPushButton(self.groupBox)
        self.btnFig_FaceColor.setObjectName("btnFig_FaceColor")
        self.gridLayout_7.addWidget(self.btnFig_FaceColor, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setIndent(10)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 1, 0, 1, 1)
        self.comboFig_Style = QtWidgets.QComboBox(self.groupBox)
        self.comboFig_Style.setObjectName("comboFig_Style")
        self.gridLayout_7.addWidget(self.comboFig_Style, 1, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.groupBox_FigureLayout = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_FigureLayout.setObjectName("groupBox_FigureLayout")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_FigureLayout)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.spinFig_marginBottom = QtWidgets.QDoubleSpinBox(self.groupBox_FigureLayout)
        self.spinFig_marginBottom.setMaximum(1.0)
        self.spinFig_marginBottom.setSingleStep(0.01)
        self.spinFig_marginBottom.setProperty("value", 0.1)
        self.spinFig_marginBottom.setObjectName("spinFig_marginBottom")
        self.gridLayout.addWidget(self.spinFig_marginBottom, 1, 1, 1, 1)
        self.spinFig_marginRight = QtWidgets.QDoubleSpinBox(self.groupBox_FigureLayout)
        self.spinFig_marginRight.setMaximum(1.0)
        self.spinFig_marginRight.setSingleStep(0.01)
        self.spinFig_marginRight.setProperty("value", 0.95)
        self.spinFig_marginRight.setObjectName("spinFig_marginRight")
        self.gridLayout.addWidget(self.spinFig_marginRight, 0, 3, 1, 1)
        self.spinFig_marginTop = QtWidgets.QDoubleSpinBox(self.groupBox_FigureLayout)
        self.spinFig_marginTop.setMaximum(1.0)
        self.spinFig_marginTop.setSingleStep(0.01)
        self.spinFig_marginTop.setProperty("value", 0.95)
        self.spinFig_marginTop.setObjectName("spinFig_marginTop")
        self.gridLayout.addWidget(self.spinFig_marginTop, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_FigureLayout)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setIndent(10)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_FigureLayout)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setIndent(10)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_FigureLayout)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setIndent(10)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_FigureLayout)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setIndent(10)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.spinFig_marginLeft = QtWidgets.QDoubleSpinBox(self.groupBox_FigureLayout)
        self.spinFig_marginLeft.setMaximum(1.0)
        self.spinFig_marginLeft.setSingleStep(0.01)
        self.spinFig_marginLeft.setProperty("value", 0.1)
        self.spinFig_marginLeft.setObjectName("spinFig_marginLeft")
        self.gridLayout.addWidget(self.spinFig_marginLeft, 0, 1, 1, 1)
        self.spinFig_wspace = QtWidgets.QDoubleSpinBox(self.groupBox_FigureLayout)
        self.spinFig_wspace.setMaximum(1.0)
        self.spinFig_wspace.setSingleStep(0.01)
        self.spinFig_wspace.setProperty("value", 0.2)
        self.spinFig_wspace.setObjectName("spinFig_wspace")
        self.gridLayout.addWidget(self.spinFig_wspace, 2, 1, 1, 1)
        self.spinFig_hspace = QtWidgets.QDoubleSpinBox(self.groupBox_FigureLayout)
        self.spinFig_hspace.setMaximum(1.0)
        self.spinFig_hspace.setSingleStep(0.01)
        self.spinFig_hspace.setProperty("value", 0.2)
        self.spinFig_hspace.setObjectName("spinFig_hspace")
        self.gridLayout.addWidget(self.spinFig_hspace, 2, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_FigureLayout)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setIndent(10)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_FigureLayout)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setIndent(10)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 2, 2, 1, 1)
        self.btnFigure_tightLayout = QtWidgets.QPushButton(self.groupBox_FigureLayout)
        self.btnFigure_tightLayout.setObjectName("btnFigure_tightLayout")
        self.gridLayout.addWidget(self.btnFigure_tightLayout, 3, 2, 1, 2)
        self.verticalLayout_11.addWidget(self.groupBox_FigureLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 105, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_Figure, icon, "")
        self.page_Axes = QtWidgets.QWidget()
        self.page_Axes.setGeometry(QtCore.QRect(0, 0, 356, 401))
        self.page_Axes.setObjectName("page_Axes")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_Axes)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.page_Axes)
        self.scrollArea_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 348, 411))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chkBoxAxes_Visible = QtWidgets.QCheckBox(self.frame_2)
        self.chkBoxAxes_Visible.setChecked(True)
        self.chkBoxAxes_Visible.setObjectName("chkBoxAxes_Visible")
        self.horizontalLayout_4.addWidget(self.chkBoxAxes_Visible)
        self.verticalLayout_13.addWidget(self.frame_2)
        self.groupBox_AxesTitle = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_AxesTitle.setCheckable(True)
        self.groupBox_AxesTitle.setChecked(True)
        self.groupBox_AxesTitle.setObjectName("groupBox_AxesTitle")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_AxesTitle)
        self.verticalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_12.setSpacing(9)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnAxes_Title = QtWidgets.QPushButton(self.groupBox_AxesTitle)
        self.btnAxes_Title.setObjectName("btnAxes_Title")
        self.horizontalLayout_9.addWidget(self.btnAxes_Title)
        self.editAxes_Title = QtWidgets.QLineEdit(self.groupBox_AxesTitle)
        self.editAxes_Title.setObjectName("editAxes_Title")
        self.horizontalLayout_9.addWidget(self.editAxes_Title)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_AxesTitle)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setIndent(5)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.spinAxes_Fontsize = QtWidgets.QSpinBox(self.groupBox_AxesTitle)
        self.spinAxes_Fontsize.setMinimum(5)
        self.spinAxes_Fontsize.setMaximum(100)
        self.spinAxes_Fontsize.setProperty("value", 16)
        self.spinAxes_Fontsize.setObjectName("spinAxes_Fontsize")
        self.horizontalLayout_10.addWidget(self.spinAxes_Fontsize)
        self.chkBoxAxes_Bold = QtWidgets.QCheckBox(self.groupBox_AxesTitle)
        self.chkBoxAxes_Bold.setChecked(True)
        self.chkBoxAxes_Bold.setObjectName("chkBoxAxes_Bold")
        self.horizontalLayout_10.addWidget(self.chkBoxAxes_Bold)
        self.chkBoxAxes_Italic = QtWidgets.QCheckBox(self.groupBox_AxesTitle)
        self.chkBoxAxes_Italic.setObjectName("chkBoxAxes_Italic")
        self.horizontalLayout_10.addWidget(self.chkBoxAxes_Italic)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btnAxes_TitleColor = QtWidgets.QPushButton(self.groupBox_AxesTitle)
        self.btnAxes_TitleColor.setObjectName("btnAxes_TitleColor")
        self.horizontalLayout_11.addWidget(self.btnAxes_TitleColor)
        self.btnAxes_TitleBackColor = QtWidgets.QPushButton(self.groupBox_AxesTitle)
        self.btnAxes_TitleBackColor.setObjectName("btnAxes_TitleBackColor")
        self.horizontalLayout_11.addWidget(self.btnAxes_TitleBackColor)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_13.addWidget(self.groupBox_AxesTitle)
        self.groupBox_AxesBack = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_AxesBack.setObjectName("groupBox_AxesBack")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_AxesBack)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setHorizontalSpacing(6)
        self.gridLayout_11.setVerticalSpacing(9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.btnAxes_FaceColor = QtWidgets.QPushButton(self.groupBox_AxesBack)
        self.btnAxes_FaceColor.setObjectName("btnAxes_FaceColor")
        self.gridLayout_11.addWidget(self.btnAxes_FaceColor, 0, 1, 1, 1)
        self.chkBoxAxes_GridX = QtWidgets.QCheckBox(self.groupBox_AxesBack)
        self.chkBoxAxes_GridX.setObjectName("chkBoxAxes_GridX")
        self.gridLayout_11.addWidget(self.chkBoxAxes_GridX, 1, 0, 1, 1)
        self.chkBoxAxes_FrameOn = QtWidgets.QCheckBox(self.groupBox_AxesBack)
        self.chkBoxAxes_FrameOn.setChecked(True)
        self.chkBoxAxes_FrameOn.setObjectName("chkBoxAxes_FrameOn")
        self.gridLayout_11.addWidget(self.chkBoxAxes_FrameOn, 0, 0, 1, 1)
        self.chkBoxAxes_GridY = QtWidgets.QCheckBox(self.groupBox_AxesBack)
        self.chkBoxAxes_GridY.setObjectName("chkBoxAxes_GridY")
        self.gridLayout_11.addWidget(self.chkBoxAxes_GridY, 1, 1, 1, 1)
        self.chkBoxAxes_MinorTicksOn = QtWidgets.QCheckBox(self.groupBox_AxesBack)
        self.chkBoxAxes_MinorTicksOn.setObjectName("chkBoxAxes_MinorTicksOn")
        self.gridLayout_11.addWidget(self.chkBoxAxes_MinorTicksOn, 2, 1, 1, 1)
        self.chkBoxAxes_AxisOn = QtWidgets.QCheckBox(self.groupBox_AxesBack)
        self.chkBoxAxes_AxisOn.setObjectName("chkBoxAxes_AxisOn")
        self.gridLayout_11.addWidget(self.chkBoxAxes_AxisOn, 2, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.groupBox_AxesBack)
        self.groupBox_AexLegend = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_AexLegend.setCheckable(True)
        self.groupBox_AexLegend.setChecked(True)
        self.groupBox_AexLegend.setObjectName("groupBox_AexLegend")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_AexLegend)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_AexLegend)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setIndent(10)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.combo_LegendLoc = QtWidgets.QComboBox(self.groupBox_AexLegend)
        self.combo_LegendLoc.setObjectName("combo_LegendLoc")
        self.gridLayout_3.addWidget(self.combo_LegendLoc, 0, 1, 1, 1)
        self.chkBoxLegend_Dragable = QtWidgets.QCheckBox(self.groupBox_AexLegend)
        self.chkBoxLegend_Dragable.setObjectName("chkBoxLegend_Dragable")
        self.gridLayout_3.addWidget(self.chkBoxLegend_Dragable, 1, 0, 1, 1)
        self.btnLegend_regenerate = QtWidgets.QPushButton(self.groupBox_AexLegend)
        self.btnLegend_regenerate.setObjectName("btnLegend_regenerate")
        self.gridLayout_3.addWidget(self.btnLegend_regenerate, 1, 1, 1, 1)
        self.verticalLayout_13.addWidget(self.groupBox_AexLegend)
        spacerItem1 = QtWidgets.QSpacerItem(20, 152, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout.addWidget(self.scrollArea_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/f17.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_Axes, icon1, "")
        self.page_Series = QtWidgets.QWidget()
        self.page_Series.setGeometry(QtCore.QRect(0, 0, 356, 401))
        self.page_Series.setObjectName("page_Series")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_Series)
        self.verticalLayout_10.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_10.setSpacing(3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.page_Series)
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 348, 393))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(11, 9, 11, 9)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.comboAxes_Lines = QtWidgets.QComboBox(self.frame_3)
        self.comboAxes_Lines.setObjectName("comboAxes_Lines")
        self.horizontalLayout_3.addWidget(self.comboAxes_Lines)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.groupBox_LineSeries = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_LineSeries.setCheckable(True)
        self.groupBox_LineSeries.setChecked(True)
        self.groupBox_LineSeries.setObjectName("groupBox_LineSeries")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_LineSeries)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setHorizontalSpacing(6)
        self.gridLayout_10.setVerticalSpacing(9)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_5 = QtWidgets.QLabel(self.groupBox_LineSeries)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setIndent(10)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboSeries_LineStyle = QtWidgets.QComboBox(self.groupBox_LineSeries)
        self.comboSeries_LineStyle.setObjectName("comboSeries_LineStyle")
        self.comboSeries_LineStyle.addItem("")
        self.comboSeries_LineStyle.addItem("")
        self.comboSeries_LineStyle.addItem("")
        self.comboSeries_LineStyle.addItem("")
        self.comboSeries_LineStyle.addItem("")
        self.gridLayout_10.addWidget(self.comboSeries_LineStyle, 0, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.groupBox_LineSeries)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setIndent(10)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 1, 0, 1, 1)
        self.comboSeries_DrawStyle = QtWidgets.QComboBox(self.groupBox_LineSeries)
        self.comboSeries_DrawStyle.setObjectName("comboSeries_DrawStyle")
        self.comboSeries_DrawStyle.addItem("")
        self.comboSeries_DrawStyle.addItem("")
        self.comboSeries_DrawStyle.addItem("")
        self.comboSeries_DrawStyle.addItem("")
        self.comboSeries_DrawStyle.addItem("")
        self.gridLayout_10.addWidget(self.comboSeries_DrawStyle, 1, 1, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.groupBox_LineSeries)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setIndent(10)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 2, 0, 1, 1)
        self.spinSeries_LineWidth = QtWidgets.QSpinBox(self.groupBox_LineSeries)
        self.spinSeries_LineWidth.setMinimum(1)
        self.spinSeries_LineWidth.setMaximum(100)
        self.spinSeries_LineWidth.setObjectName("spinSeries_LineWidth")
        self.gridLayout_10.addWidget(self.spinSeries_LineWidth, 2, 1, 1, 1)
        self.btnSeries_LineColor = QtWidgets.QPushButton(self.groupBox_LineSeries)
        self.btnSeries_LineColor.setObjectName("btnSeries_LineColor")
        self.gridLayout_10.addWidget(self.btnSeries_LineColor, 2, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_LineSeries)
        self.groupBox_Marker = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_Marker.setCheckable(True)
        self.groupBox_Marker.setChecked(True)
        self.groupBox_Marker.setObjectName("groupBox_Marker")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_Marker)
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setHorizontalSpacing(6)
        self.gridLayout_9.setVerticalSpacing(9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btnMarker_Color = QtWidgets.QPushButton(self.groupBox_Marker)
        self.btnMarker_Color.setObjectName("btnMarker_Color")
        self.gridLayout_9.addWidget(self.btnMarker_Color, 1, 2, 1, 1)
        self.btnMarker_EdgeColor = QtWidgets.QPushButton(self.groupBox_Marker)
        self.btnMarker_EdgeColor.setObjectName("btnMarker_EdgeColor")
        self.gridLayout_9.addWidget(self.btnMarker_EdgeColor, 2, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_Marker)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setIndent(10)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_Marker)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setIndent(10)
        self.label_16.setObjectName("label_16")
        self.gridLayout_9.addWidget(self.label_16, 0, 0, 1, 1)
        self.spinMarker_EdgeWidth = QtWidgets.QSpinBox(self.groupBox_Marker)
        self.spinMarker_EdgeWidth.setMinimum(0)
        self.spinMarker_EdgeWidth.setObjectName("spinMarker_EdgeWidth")
        self.gridLayout_9.addWidget(self.spinMarker_EdgeWidth, 2, 1, 1, 1)
        self.comboMarker_Shape = QtWidgets.QComboBox(self.groupBox_Marker)
        self.comboMarker_Shape.setObjectName("comboMarker_Shape")
        self.comboMarker_Shape.addItem("")
        self.comboMarker_Shape.addItem("")
        self.comboMarker_Shape.addItem("")
        self.comboMarker_Shape.addItem("")
        self.comboMarker_Shape.addItem("")
        self.comboMarker_Shape.addItem("")
        self.comboMarker_Shape.addItem("")
        self.comboMarker_Shape.addItem("")
        self.comboMarker_Shape.addItem("")
        self.comboMarker_Shape.addItem("")
        self.comboMarker_Shape.addItem("")
        self.comboMarker_Shape.addItem("")
        self.comboMarker_Shape.addItem("")
        self.comboMarker_Shape.addItem("")
        self.gridLayout_9.addWidget(self.comboMarker_Shape, 0, 1, 1, 2)
        self.spinMarker_Size = QtWidgets.QSpinBox(self.groupBox_Marker)
        self.spinMarker_Size.setMinimum(1)
        self.spinMarker_Size.setMaximum(100)
        self.spinMarker_Size.setProperty("value", 2)
        self.spinMarker_Size.setObjectName("spinMarker_Size")
        self.gridLayout_9.addWidget(self.spinMarker_Size, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_Marker)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setIndent(10)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_Marker)
        spacerItem2 = QtWidgets.QSpacerItem(20, 286, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_10.addWidget(self.scrollArea_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/dis3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_Series, icon2, "")
        self.page_AxisX = QtWidgets.QWidget()
        self.page_AxisX.setGeometry(QtCore.QRect(0, 0, 356, 401))
        self.page_AxisX.setObjectName("page_AxisX")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_AxisX)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.page_AxisX)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 350, 547))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_AxisX = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_AxisX.setFlat(True)
        self.groupBox_AxisX.setCheckable(True)
        self.groupBox_AxisX.setObjectName("groupBox_AxisX")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_AxisX)
        self.verticalLayout_2.setContentsMargins(0, 11, 0, 11)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxX_Lim = QtWidgets.QGroupBox(self.groupBox_AxisX)
        self.groupBoxX_Lim.setObjectName("groupBoxX_Lim")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxX_Lim)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBoxX_Lim)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setIndent(10)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.spinAxisX_Min = QtWidgets.QDoubleSpinBox(self.groupBoxX_Lim)
        self.spinAxisX_Min.setMinimum(-1000.0)
        self.spinAxisX_Min.setMaximum(1000.0)
        self.spinAxisX_Min.setObjectName("spinAxisX_Min")
        self.gridLayout_4.addWidget(self.spinAxisX_Min, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBoxX_Lim)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setIndent(10)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.spinAxisX_Max = QtWidgets.QDoubleSpinBox(self.groupBoxX_Lim)
        self.spinAxisX_Max.setMinimum(-1000.0)
        self.spinAxisX_Max.setMaximum(1000.0)
        self.spinAxisX_Max.setProperty("value", 10.0)
        self.spinAxisX_Max.setObjectName("spinAxisX_Max")
        self.gridLayout_4.addWidget(self.spinAxisX_Max, 1, 1, 1, 1)
        self.btnAxisX_setBound = QtWidgets.QPushButton(self.groupBoxX_Lim)
        self.btnAxisX_setBound.setObjectName("btnAxisX_setBound")
        self.gridLayout_4.addWidget(self.btnAxisX_setBound, 1, 2, 1, 1)
        self.comboAxisX_Scale = QtWidgets.QComboBox(self.groupBoxX_Lim)
        self.comboAxisX_Scale.setObjectName("comboAxisX_Scale")
        self.comboAxisX_Scale.addItem("")
        self.comboAxisX_Scale.addItem("")
        self.comboAxisX_Scale.addItem("")
        self.comboAxisX_Scale.addItem("")
        self.gridLayout_4.addWidget(self.comboAxisX_Scale, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBoxX_Lim)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setIndent(10)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 2, 0, 1, 1)
        self.chkBoxAxisX_Invert = QtWidgets.QCheckBox(self.groupBoxX_Lim)
        self.chkBoxAxisX_Invert.setObjectName("chkBoxAxisX_Invert")
        self.gridLayout_4.addWidget(self.chkBoxAxisX_Invert, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBoxX_Lim)
        self.groupBox_AxisXLabel = QtWidgets.QGroupBox(self.groupBox_AxisX)
        self.groupBox_AxisXLabel.setCheckable(True)
        self.groupBox_AxisXLabel.setObjectName("groupBox_AxisXLabel")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_AxisXLabel)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnAxisX_setLabel = QtWidgets.QPushButton(self.groupBox_AxisXLabel)
        self.btnAxisX_setLabel.setObjectName("btnAxisX_setLabel")
        self.gridLayout_2.addWidget(self.btnAxisX_setLabel, 0, 0, 1, 1)
        self.editAxisX_Label = QtWidgets.QLineEdit(self.groupBox_AxisXLabel)
        self.editAxisX_Label.setObjectName("editAxisX_Label")
        self.gridLayout_2.addWidget(self.editAxisX_Label, 0, 1, 1, 1)
        self.btnAxisX_LabelColor = QtWidgets.QPushButton(self.groupBox_AxisXLabel)
        self.btnAxisX_LabelColor.setObjectName("btnAxisX_LabelColor")
        self.gridLayout_2.addWidget(self.btnAxisX_LabelColor, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.groupBox_AxisXLabel)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        self.spinAxisX_LabelFontsize = QtWidgets.QSpinBox(self.groupBox_AxisXLabel)
        self.spinAxisX_LabelFontsize.setMinimum(5)
        self.spinAxisX_LabelFontsize.setMaximum(100)
        self.spinAxisX_LabelFontsize.setProperty("value", 16)
        self.spinAxisX_LabelFontsize.setObjectName("spinAxisX_LabelFontsize")
        self.horizontalLayout_2.addWidget(self.spinAxisX_LabelFontsize)
        self.chkBoxAxisX_LabelBold = QtWidgets.QCheckBox(self.groupBox_AxisXLabel)
        self.chkBoxAxisX_LabelBold.setChecked(True)
        self.chkBoxAxisX_LabelBold.setObjectName("chkBoxAxisX_LabelBold")
        self.horizontalLayout_2.addWidget(self.chkBoxAxisX_LabelBold)
        self.chkBoxAxisX_LabelItalic = QtWidgets.QCheckBox(self.groupBox_AxisXLabel)
        self.chkBoxAxisX_LabelItalic.setObjectName("chkBoxAxisX_LabelItalic")
        self.horizontalLayout_2.addWidget(self.chkBoxAxisX_LabelItalic)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_AxisXLabel)
        self.groupBoxAxisX_TickLabel = QtWidgets.QGroupBox(self.groupBox_AxisX)
        self.groupBoxAxisX_TickLabel.setCheckable(True)
        self.groupBoxAxisX_TickLabel.setObjectName("groupBoxAxisX_TickLabel")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBoxAxisX_TickLabel)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btnAxisX_TickLabFormat = QtWidgets.QPushButton(self.groupBoxAxisX_TickLabel)
        self.btnAxisX_TickLabFormat.setObjectName("btnAxisX_TickLabFormat")
        self.gridLayout_8.addWidget(self.btnAxisX_TickLabFormat, 0, 0, 1, 1)
        self.editAxisX_TickLabFormat = QtWidgets.QLineEdit(self.groupBoxAxisX_TickLabel)
        self.editAxisX_TickLabFormat.setObjectName("editAxisX_TickLabFormat")
        self.gridLayout_8.addWidget(self.editAxisX_TickLabFormat, 0, 1, 1, 1)
        self.btnAxisX_TickLabColor = QtWidgets.QPushButton(self.groupBoxAxisX_TickLabel)
        self.btnAxisX_TickLabColor.setObjectName("btnAxisX_TickLabColor")
        self.gridLayout_8.addWidget(self.btnAxisX_TickLabColor, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_20 = QtWidgets.QLabel(self.groupBoxAxisX_TickLabel)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.label_20)
        self.spinAxisX_TickLabelFontsize = QtWidgets.QSpinBox(self.groupBoxAxisX_TickLabel)
        self.spinAxisX_TickLabelFontsize.setMinimum(5)
        self.spinAxisX_TickLabelFontsize.setMaximum(100)
        self.spinAxisX_TickLabelFontsize.setProperty("value", 16)
        self.spinAxisX_TickLabelFontsize.setObjectName("spinAxisX_TickLabelFontsize")
        self.horizontalLayout_5.addWidget(self.spinAxisX_TickLabelFontsize)
        self.chkBoxAxisX_TickLabBottom = QtWidgets.QCheckBox(self.groupBoxAxisX_TickLabel)
        self.chkBoxAxisX_TickLabBottom.setChecked(True)
        self.chkBoxAxisX_TickLabBottom.setObjectName("chkBoxAxisX_TickLabBottom")
        self.horizontalLayout_5.addWidget(self.chkBoxAxisX_TickLabBottom)
        self.chkBoxAxisX_TickLabTop = QtWidgets.QCheckBox(self.groupBoxAxisX_TickLabel)
        self.chkBoxAxisX_TickLabTop.setObjectName("chkBoxAxisX_TickLabTop")
        self.horizontalLayout_5.addWidget(self.chkBoxAxisX_TickLabTop)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBoxAxisX_TickLabel)
        self.gBoxAxisX_majorTickGrid = QtWidgets.QGroupBox(self.groupBox_AxisX)
        self.gBoxAxisX_majorTickGrid.setCheckable(False)
        self.gBoxAxisX_majorTickGrid.setObjectName("gBoxAxisX_majorTickGrid")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gBoxAxisX_majorTickGrid)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.chkBoxX_majorTickBottom = QtWidgets.QCheckBox(self.gBoxAxisX_majorTickGrid)
        self.chkBoxX_majorTickBottom.setChecked(True)
        self.chkBoxX_majorTickBottom.setObjectName("chkBoxX_majorTickBottom")
        self.gridLayout_5.addWidget(self.chkBoxX_majorTickBottom, 0, 0, 1, 1)
        self.chkBoxX_majorGrid = QtWidgets.QCheckBox(self.gBoxAxisX_majorTickGrid)
        self.chkBoxX_majorGrid.setObjectName("chkBoxX_majorGrid")
        self.gridLayout_5.addWidget(self.chkBoxX_majorGrid, 1, 0, 1, 1)
        self.btnLineColorX_majorTick = QtWidgets.QPushButton(self.gBoxAxisX_majorTickGrid)
        self.btnLineColorX_majorTick.setObjectName("btnLineColorX_majorTick")
        self.gridLayout_5.addWidget(self.btnLineColorX_majorTick, 0, 3, 1, 1)
        self.chkBoxX_majorTickTop = QtWidgets.QCheckBox(self.gBoxAxisX_majorTickGrid)
        self.chkBoxX_majorTickTop.setObjectName("chkBoxX_majorTickTop")
        self.gridLayout_5.addWidget(self.chkBoxX_majorTickTop, 0, 2, 1, 1)
        self.btnLineColorX_majorGrid = QtWidgets.QPushButton(self.gBoxAxisX_majorTickGrid)
        self.btnLineColorX_majorGrid.setEnabled(True)
        self.btnLineColorX_majorGrid.setObjectName("btnLineColorX_majorGrid")
        self.gridLayout_5.addWidget(self.btnLineColorX_majorGrid, 1, 3, 1, 1)
        self.comboLineStyle_XmajorGrid = QtWidgets.QComboBox(self.gBoxAxisX_majorTickGrid)
        self.comboLineStyle_XmajorGrid.setEnabled(True)
        self.comboLineStyle_XmajorGrid.setObjectName("comboLineStyle_XmajorGrid")
        self.comboLineStyle_XmajorGrid.addItem("")
        self.comboLineStyle_XmajorGrid.addItem("")
        self.comboLineStyle_XmajorGrid.addItem("")
        self.comboLineStyle_XmajorGrid.addItem("")
        self.comboLineStyle_XmajorGrid.addItem("")
        self.gridLayout_5.addWidget(self.comboLineStyle_XmajorGrid, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.gBoxAxisX_majorTickGrid)
        self.gBoxAxisX_minorTickGrid = QtWidgets.QGroupBox(self.groupBox_AxisX)
        self.gBoxAxisX_minorTickGrid.setCheckable(False)
        self.gBoxAxisX_minorTickGrid.setObjectName("gBoxAxisX_minorTickGrid")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gBoxAxisX_minorTickGrid)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.chkBoxX_minorTickBottom = QtWidgets.QCheckBox(self.gBoxAxisX_minorTickGrid)
        self.chkBoxX_minorTickBottom.setObjectName("chkBoxX_minorTickBottom")
        self.gridLayout_6.addWidget(self.chkBoxX_minorTickBottom, 0, 0, 1, 1)
        self.chkBoxX_minorGrid = QtWidgets.QCheckBox(self.gBoxAxisX_minorTickGrid)
        self.chkBoxX_minorGrid.setObjectName("chkBoxX_minorGrid")
        self.gridLayout_6.addWidget(self.chkBoxX_minorGrid, 1, 0, 1, 1)
        self.btnLineColorX_minorTick = QtWidgets.QPushButton(self.gBoxAxisX_minorTickGrid)
        self.btnLineColorX_minorTick.setEnabled(True)
        self.btnLineColorX_minorTick.setObjectName("btnLineColorX_minorTick")
        self.gridLayout_6.addWidget(self.btnLineColorX_minorTick, 0, 3, 1, 1)
        self.btnLineColorX_minorGrid = QtWidgets.QPushButton(self.gBoxAxisX_minorTickGrid)
        self.btnLineColorX_minorGrid.setEnabled(True)
        self.btnLineColorX_minorGrid.setObjectName("btnLineColorX_minorGrid")
        self.gridLayout_6.addWidget(self.btnLineColorX_minorGrid, 1, 3, 1, 1)
        self.comboLineStyle_XminorGrid = QtWidgets.QComboBox(self.gBoxAxisX_minorTickGrid)
        self.comboLineStyle_XminorGrid.setEnabled(True)
        self.comboLineStyle_XminorGrid.setObjectName("comboLineStyle_XminorGrid")
        self.comboLineStyle_XminorGrid.addItem("")
        self.comboLineStyle_XminorGrid.addItem("")
        self.comboLineStyle_XminorGrid.addItem("")
        self.comboLineStyle_XminorGrid.addItem("")
        self.comboLineStyle_XminorGrid.addItem("")
        self.gridLayout_6.addWidget(self.comboLineStyle_XminorGrid, 1, 1, 1, 1)
        self.chkBoxX_minorTickTop = QtWidgets.QCheckBox(self.gBoxAxisX_minorTickGrid)
        self.chkBoxX_minorTickTop.setObjectName("chkBoxX_minorTickTop")
        self.gridLayout_6.addWidget(self.chkBoxX_minorTickTop, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gBoxAxisX_minorTickGrid)
        spacerItem3 = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout_8.addWidget(self.groupBox_AxisX)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/602.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_AxisX, icon3, "")
        self.page_AxisY = QtWidgets.QWidget()
        self.page_AxisY.setGeometry(QtCore.QRect(0, 0, 356, 401))
        self.page_AxisY.setObjectName("page_AxisY")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_AxisY)
        self.verticalLayout_14.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.page_AxisY)
        self.scrollArea_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.scrollArea_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 350, 565))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_AxisY = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_5)
        self.groupBox_AxisY.setFlat(True)
        self.groupBox_AxisY.setCheckable(True)
        self.groupBox_AxisY.setObjectName("groupBox_AxisY")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_AxisY)
        self.verticalLayout_7.setContentsMargins(0, 11, 0, 11)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBoxY_Lim = QtWidgets.QGroupBox(self.groupBox_AxisY)
        self.groupBoxY_Lim.setObjectName("groupBoxY_Lim")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBoxY_Lim)
        self.gridLayout_12.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_12.setHorizontalSpacing(6)
        self.gridLayout_12.setVerticalSpacing(9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_9 = QtWidgets.QLabel(self.groupBoxY_Lim)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setIndent(10)
        self.label_9.setObjectName("label_9")
        self.gridLayout_12.addWidget(self.label_9, 0, 0, 1, 1)
        self.spinAxisY_Min = QtWidgets.QDoubleSpinBox(self.groupBoxY_Lim)
        self.spinAxisY_Min.setMinimum(-1000.0)
        self.spinAxisY_Min.setMaximum(1000.0)
        self.spinAxisY_Min.setObjectName("spinAxisY_Min")
        self.gridLayout_12.addWidget(self.spinAxisY_Min, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBoxY_Lim)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setIndent(10)
        self.label_21.setObjectName("label_21")
        self.gridLayout_12.addWidget(self.label_21, 1, 0, 1, 1)
        self.spinAxisY_Max = QtWidgets.QDoubleSpinBox(self.groupBoxY_Lim)
        self.spinAxisY_Max.setMinimum(-1000.0)
        self.spinAxisY_Max.setMaximum(1000.0)
        self.spinAxisY_Max.setProperty("value", 10.0)
        self.spinAxisY_Max.setObjectName("spinAxisY_Max")
        self.gridLayout_12.addWidget(self.spinAxisY_Max, 1, 1, 1, 1)
        self.btnAxisY_setBound = QtWidgets.QPushButton(self.groupBoxY_Lim)
        self.btnAxisY_setBound.setObjectName("btnAxisY_setBound")
        self.gridLayout_12.addWidget(self.btnAxisY_setBound, 1, 2, 1, 1)
        self.comboAxisY_Scale = QtWidgets.QComboBox(self.groupBoxY_Lim)
        self.comboAxisY_Scale.setObjectName("comboAxisY_Scale")
        self.comboAxisY_Scale.addItem("")
        self.comboAxisY_Scale.addItem("")
        self.comboAxisY_Scale.addItem("")
        self.comboAxisY_Scale.addItem("")
        self.gridLayout_12.addWidget(self.comboAxisY_Scale, 2, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBoxY_Lim)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setIndent(10)
        self.label_27.setObjectName("label_27")
        self.gridLayout_12.addWidget(self.label_27, 2, 0, 1, 1)
        self.chkBoxAxisY_Invert = QtWidgets.QCheckBox(self.groupBoxY_Lim)
        self.chkBoxAxisY_Invert.setObjectName("chkBoxAxisY_Invert")
        self.gridLayout_12.addWidget(self.chkBoxAxisY_Invert, 2, 2, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBoxY_Lim)
        self.groupBox_AxisYLabel = QtWidgets.QGroupBox(self.groupBox_AxisY)
        self.groupBox_AxisYLabel.setCheckable(True)
        self.groupBox_AxisYLabel.setObjectName("groupBox_AxisYLabel")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_AxisYLabel)
        self.gridLayout_13.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_13.setHorizontalSpacing(6)
        self.gridLayout_13.setVerticalSpacing(9)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.btnAxisY_setLabel = QtWidgets.QPushButton(self.groupBox_AxisYLabel)
        self.btnAxisY_setLabel.setObjectName("btnAxisY_setLabel")
        self.gridLayout_13.addWidget(self.btnAxisY_setLabel, 0, 0, 1, 1)
        self.editAxisY_Label = QtWidgets.QLineEdit(self.groupBox_AxisYLabel)
        self.editAxisY_Label.setObjectName("editAxisY_Label")
        self.gridLayout_13.addWidget(self.editAxisY_Label, 0, 1, 1, 1)
        self.btnAxisY_LabelColor = QtWidgets.QPushButton(self.groupBox_AxisYLabel)
        self.btnAxisY_LabelColor.setObjectName("btnAxisY_LabelColor")
        self.gridLayout_13.addWidget(self.btnAxisY_LabelColor, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_22 = QtWidgets.QLabel(self.groupBox_AxisYLabel)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_8.addWidget(self.label_22)
        self.spinAxisY_LabelFontsize = QtWidgets.QSpinBox(self.groupBox_AxisYLabel)
        self.spinAxisY_LabelFontsize.setMinimum(5)
        self.spinAxisY_LabelFontsize.setMaximum(100)
        self.spinAxisY_LabelFontsize.setProperty("value", 16)
        self.spinAxisY_LabelFontsize.setObjectName("spinAxisY_LabelFontsize")
        self.horizontalLayout_8.addWidget(self.spinAxisY_LabelFontsize)
        self.chkBoxAxisY_LabelBold = QtWidgets.QCheckBox(self.groupBox_AxisYLabel)
        self.chkBoxAxisY_LabelBold.setChecked(True)
        self.chkBoxAxisY_LabelBold.setObjectName("chkBoxAxisY_LabelBold")
        self.horizontalLayout_8.addWidget(self.chkBoxAxisY_LabelBold)
        self.chkBoxAxisY_LabelItalic = QtWidgets.QCheckBox(self.groupBox_AxisYLabel)
        self.chkBoxAxisY_LabelItalic.setObjectName("chkBoxAxisY_LabelItalic")
        self.horizontalLayout_8.addWidget(self.chkBoxAxisY_LabelItalic)
        self.gridLayout_13.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_AxisYLabel)
        self.groupBoxAxisY_TickLabel = QtWidgets.QGroupBox(self.groupBox_AxisY)
        self.groupBoxAxisY_TickLabel.setCheckable(True)
        self.groupBoxAxisY_TickLabel.setObjectName("groupBoxAxisY_TickLabel")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBoxAxisY_TickLabel)
        self.gridLayout_14.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_14.setHorizontalSpacing(6)
        self.gridLayout_14.setVerticalSpacing(9)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.btnAxisY_TickLabFormat = QtWidgets.QPushButton(self.groupBoxAxisY_TickLabel)
        self.btnAxisY_TickLabFormat.setObjectName("btnAxisY_TickLabFormat")
        self.gridLayout_14.addWidget(self.btnAxisY_TickLabFormat, 0, 0, 1, 1)
        self.editAxisY_TickLabFormat = QtWidgets.QLineEdit(self.groupBoxAxisY_TickLabel)
        self.editAxisY_TickLabFormat.setObjectName("editAxisY_TickLabFormat")
        self.gridLayout_14.addWidget(self.editAxisY_TickLabFormat, 0, 1, 1, 1)
        self.btnAxisY_TickLabColor = QtWidgets.QPushButton(self.groupBoxAxisY_TickLabel)
        self.btnAxisY_TickLabColor.setObjectName("btnAxisY_TickLabColor")
        self.gridLayout_14.addWidget(self.btnAxisY_TickLabColor, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_23 = QtWidgets.QLabel(self.groupBoxAxisY_TickLabel)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        self.spinAxisY_TickLabelFontsize = QtWidgets.QSpinBox(self.groupBoxAxisY_TickLabel)
        self.spinAxisY_TickLabelFontsize.setMinimum(5)
        self.spinAxisY_TickLabelFontsize.setMaximum(100)
        self.spinAxisY_TickLabelFontsize.setProperty("value", 16)
        self.spinAxisY_TickLabelFontsize.setObjectName("spinAxisY_TickLabelFontsize")
        self.horizontalLayout_12.addWidget(self.spinAxisY_TickLabelFontsize)
        self.chkBoxAxisY_TickLabLeft = QtWidgets.QCheckBox(self.groupBoxAxisY_TickLabel)
        self.chkBoxAxisY_TickLabLeft.setChecked(True)
        self.chkBoxAxisY_TickLabLeft.setObjectName("chkBoxAxisY_TickLabLeft")
        self.horizontalLayout_12.addWidget(self.chkBoxAxisY_TickLabLeft)
        self.chkBoxAxisY_TickLabRight = QtWidgets.QCheckBox(self.groupBoxAxisY_TickLabel)
        self.chkBoxAxisY_TickLabRight.setObjectName("chkBoxAxisY_TickLabRight")
        self.horizontalLayout_12.addWidget(self.chkBoxAxisY_TickLabRight)
        self.gridLayout_14.addLayout(self.horizontalLayout_12, 1, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBoxAxisY_TickLabel)
        self.gBoxAxisY_majorTickGrid = QtWidgets.QGroupBox(self.groupBox_AxisY)
        self.gBoxAxisY_majorTickGrid.setCheckable(False)
        self.gBoxAxisY_majorTickGrid.setObjectName("gBoxAxisY_majorTickGrid")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gBoxAxisY_majorTickGrid)
        self.gridLayout_15.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_15.setHorizontalSpacing(6)
        self.gridLayout_15.setVerticalSpacing(9)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.chkBoxY_majorTickLeft = QtWidgets.QCheckBox(self.gBoxAxisY_majorTickGrid)
        self.chkBoxY_majorTickLeft.setChecked(True)
        self.chkBoxY_majorTickLeft.setObjectName("chkBoxY_majorTickLeft")
        self.gridLayout_15.addWidget(self.chkBoxY_majorTickLeft, 0, 0, 1, 1)
        self.chkBoxY_majorGrid = QtWidgets.QCheckBox(self.gBoxAxisY_majorTickGrid)
        self.chkBoxY_majorGrid.setObjectName("chkBoxY_majorGrid")
        self.gridLayout_15.addWidget(self.chkBoxY_majorGrid, 1, 0, 1, 1)
        self.btnLineColorY_majorTick = QtWidgets.QPushButton(self.gBoxAxisY_majorTickGrid)
        self.btnLineColorY_majorTick.setObjectName("btnLineColorY_majorTick")
        self.gridLayout_15.addWidget(self.btnLineColorY_majorTick, 0, 3, 1, 1)
        self.btnLineColorY_majorGrid = QtWidgets.QPushButton(self.gBoxAxisY_majorTickGrid)
        self.btnLineColorY_majorGrid.setEnabled(True)
        self.btnLineColorY_majorGrid.setObjectName("btnLineColorY_majorGrid")
        self.gridLayout_15.addWidget(self.btnLineColorY_majorGrid, 1, 3, 1, 1)
        self.comboLineStyle_YmajorGrid = QtWidgets.QComboBox(self.gBoxAxisY_majorTickGrid)
        self.comboLineStyle_YmajorGrid.setEnabled(True)
        self.comboLineStyle_YmajorGrid.setObjectName("comboLineStyle_YmajorGrid")
        self.comboLineStyle_YmajorGrid.addItem("")
        self.comboLineStyle_YmajorGrid.addItem("")
        self.comboLineStyle_YmajorGrid.addItem("")
        self.comboLineStyle_YmajorGrid.addItem("")
        self.comboLineStyle_YmajorGrid.addItem("")
        self.gridLayout_15.addWidget(self.comboLineStyle_YmajorGrid, 1, 1, 1, 1)
        self.chkBoxY_majorTickRight = QtWidgets.QCheckBox(self.gBoxAxisY_majorTickGrid)
        self.chkBoxY_majorTickRight.setObjectName("chkBoxY_majorTickRight")
        self.gridLayout_15.addWidget(self.chkBoxY_majorTickRight, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.gBoxAxisY_majorTickGrid)
        self.gBoxAxisY_minorTickGrid = QtWidgets.QGroupBox(self.groupBox_AxisY)
        self.gBoxAxisY_minorTickGrid.setCheckable(False)
        self.gBoxAxisY_minorTickGrid.setObjectName("gBoxAxisY_minorTickGrid")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.gBoxAxisY_minorTickGrid)
        self.gridLayout_16.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_16.setHorizontalSpacing(6)
        self.gridLayout_16.setVerticalSpacing(9)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.chkBoxY_minorTickLeft = QtWidgets.QCheckBox(self.gBoxAxisY_minorTickGrid)
        self.chkBoxY_minorTickLeft.setObjectName("chkBoxY_minorTickLeft")
        self.gridLayout_16.addWidget(self.chkBoxY_minorTickLeft, 0, 0, 1, 1)
        self.chkBoxY_minorGrid = QtWidgets.QCheckBox(self.gBoxAxisY_minorTickGrid)
        self.chkBoxY_minorGrid.setObjectName("chkBoxY_minorGrid")
        self.gridLayout_16.addWidget(self.chkBoxY_minorGrid, 1, 0, 1, 1)
        self.btnLineColorY_minorTick = QtWidgets.QPushButton(self.gBoxAxisY_minorTickGrid)
        self.btnLineColorY_minorTick.setEnabled(True)
        self.btnLineColorY_minorTick.setObjectName("btnLineColorY_minorTick")
        self.gridLayout_16.addWidget(self.btnLineColorY_minorTick, 0, 3, 1, 1)
        self.btnLineColorY_minorGrid = QtWidgets.QPushButton(self.gBoxAxisY_minorTickGrid)
        self.btnLineColorY_minorGrid.setEnabled(True)
        self.btnLineColorY_minorGrid.setObjectName("btnLineColorY_minorGrid")
        self.gridLayout_16.addWidget(self.btnLineColorY_minorGrid, 1, 3, 1, 1)
        self.comboLineStyle_YminorGrid = QtWidgets.QComboBox(self.gBoxAxisY_minorTickGrid)
        self.comboLineStyle_YminorGrid.setEnabled(True)
        self.comboLineStyle_YminorGrid.setObjectName("comboLineStyle_YminorGrid")
        self.comboLineStyle_YminorGrid.addItem("")
        self.comboLineStyle_YminorGrid.addItem("")
        self.comboLineStyle_YminorGrid.addItem("")
        self.comboLineStyle_YminorGrid.addItem("")
        self.comboLineStyle_YminorGrid.addItem("")
        self.gridLayout_16.addWidget(self.comboLineStyle_YminorGrid, 1, 1, 1, 1)
        self.chkBoxY_minorTickRight = QtWidgets.QCheckBox(self.gBoxAxisY_minorTickGrid)
        self.chkBoxY_minorTickRight.setObjectName("chkBoxY_minorTickRight")
        self.gridLayout_16.addWidget(self.chkBoxY_minorTickRight, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.gBoxAxisY_minorTickGrid)
        spacerItem4 = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.verticalLayout_9.addWidget(self.groupBox_AxisY)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_14.addWidget(self.scrollArea_5)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/604.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_AxisY, icon4, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.actQuit = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/exit_24.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actQuit.setIcon(icon5)
        self.actQuit.setObjectName("actQuit")

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QChart绘图详细功能"))
        self.groupBox_suptitle.setTitle(_translate("MainWindow", "1.1 suptitle 标题"))
        self.btnFig_Title.setToolTip(_translate("MainWindow", "设置标题文字"))
        self.btnFig_Title.setText(_translate("MainWindow", "设置标题"))
        self.editFig_Title.setText(_translate("MainWindow", "suptitle:matplotlib in Qt5 GUI"))
        self.label_12.setText(_translate("MainWindow", "字体大小"))
        self.chkBoxFig_Bold.setText(_translate("MainWindow", "粗体"))
        self.chkBoxFig_Italic.setText(_translate("MainWindow", "斜体"))
        self.btnFig_TitleColor.setText(_translate("MainWindow", "文字颜色"))
        self.btnFig_TitleBackColor.setText(_translate("MainWindow", "背景颜色"))
        self.groupBox.setTitle(_translate("MainWindow", "1.2 背景与边框"))
        self.chkBoxFig_FrameOn.setText(_translate("MainWindow", "显示背景和边框"))
        self.btnFig_FaceColor.setText(_translate("MainWindow", "设置背景颜色"))
        self.label_10.setText(_translate("MainWindow", "图表样式"))
        self.groupBox_FigureLayout.setTitle(_translate("MainWindow", "1.3 绘图区边距与子图间隔"))
        self.label.setText(_translate("MainWindow", "Left"))
        self.label_3.setText(_translate("MainWindow", "Right"))
        self.label_2.setText(_translate("MainWindow", "Bottom"))
        self.label_4.setText(_translate("MainWindow", "Top"))
        self.label_24.setText(_translate("MainWindow", "wspace"))
        self.label_25.setText(_translate("MainWindow", "hspace"))
        self.btnFigure_tightLayout.setText(_translate("MainWindow", "tight_layout布局"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_Figure), _translate("MainWindow", "1. Figure操作"))
        self.chkBoxAxes_Visible.setText(_translate("MainWindow", "当前子图可见"))
        self.groupBox_AxesTitle.setTitle(_translate("MainWindow", "2.1 子图标题"))
        self.btnAxes_Title.setToolTip(_translate("MainWindow", "设置标题文字"))
        self.btnAxes_Title.setText(_translate("MainWindow", "设置标题"))
        self.editAxes_Title.setText(_translate("MainWindow", "三角函数曲线"))
        self.label_13.setText(_translate("MainWindow", "字体大小"))
        self.chkBoxAxes_Bold.setText(_translate("MainWindow", "粗体"))
        self.chkBoxAxes_Italic.setText(_translate("MainWindow", "斜体"))
        self.btnAxes_TitleColor.setText(_translate("MainWindow", "文字颜色"))
        self.btnAxes_TitleBackColor.setText(_translate("MainWindow", "背景颜色"))
        self.groupBox_AxesBack.setTitle(_translate("MainWindow", "2.2 子图外观"))
        self.btnAxes_FaceColor.setText(_translate("MainWindow", "设置背景颜色"))
        self.chkBoxAxes_GridX.setText(_translate("MainWindow", "显示X网格线"))
        self.chkBoxAxes_FrameOn.setText(_translate("MainWindow", "显示背景和边框"))
        self.chkBoxAxes_GridY.setText(_translate("MainWindow", "显示Y网格线"))
        self.chkBoxAxes_MinorTicksOn.setText(_translate("MainWindow", "显示次刻度"))
        self.chkBoxAxes_AxisOn.setText(_translate("MainWindow", "显示坐标轴"))
        self.groupBox_AexLegend.setTitle(_translate("MainWindow", "2.3 图例"))
        self.label_6.setText(_translate("MainWindow", "图例位置"))
        self.chkBoxLegend_Dragable.setText(_translate("MainWindow", "图例可拖动"))
        self.btnLegend_regenerate.setText(_translate("MainWindow", "重新生成图例"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_Axes), _translate("MainWindow", "2. Axes子图操作"))
        self.label_8.setText(_translate("MainWindow", "3.1 当前操作曲线"))
        self.groupBox_LineSeries.setTitle(_translate("MainWindow", "3.2 曲线外观"))
        self.label_5.setText(_translate("MainWindow", "曲线样式"))
        self.comboSeries_LineStyle.setItemText(0, _translate("MainWindow", "-"))
        self.comboSeries_LineStyle.setItemText(1, _translate("MainWindow", "--"))
        self.comboSeries_LineStyle.setItemText(2, _translate("MainWindow", "-."))
        self.comboSeries_LineStyle.setItemText(3, _translate("MainWindow", ":"))
        self.comboSeries_LineStyle.setItemText(4, _translate("MainWindow", "None"))
        self.label_14.setText(_translate("MainWindow", "绘图样式"))
        self.comboSeries_DrawStyle.setItemText(0, _translate("MainWindow", "default"))
        self.comboSeries_DrawStyle.setItemText(1, _translate("MainWindow", "steps"))
        self.comboSeries_DrawStyle.setItemText(2, _translate("MainWindow", "steps-pre"))
        self.comboSeries_DrawStyle.setItemText(3, _translate("MainWindow", "steps-mid"))
        self.comboSeries_DrawStyle.setItemText(4, _translate("MainWindow", "steps-post"))
        self.label_15.setText(_translate("MainWindow", "线  宽"))
        self.btnSeries_LineColor.setText(_translate("MainWindow", "曲线颜色"))
        self.groupBox_Marker.setTitle(_translate("MainWindow", "3.3 标记点"))
        self.btnMarker_Color.setText(_translate("MainWindow", "标记点颜色"))
        self.btnMarker_EdgeColor.setText(_translate("MainWindow", "边线颜色"))
        self.label_18.setText(_translate("MainWindow", "边线线宽"))
        self.label_16.setText(_translate("MainWindow", "标记点形状"))
        self.comboMarker_Shape.setItemText(0, _translate("MainWindow", "o[circle marker]"))
        self.comboMarker_Shape.setItemText(1, _translate("MainWindow", "v[triangle_down marker]"))
        self.comboMarker_Shape.setItemText(2, _translate("MainWindow", "^[triangle_up marker]"))
        self.comboMarker_Shape.setItemText(3, _translate("MainWindow", "<[triangle_left marker]"))
        self.comboMarker_Shape.setItemText(4, _translate("MainWindow", ">[triangle_right marker]"))
        self.comboMarker_Shape.setItemText(5, _translate("MainWindow", "s[square marker]"))
        self.comboMarker_Shape.setItemText(6, _translate("MainWindow", "p[pentagon marker]"))
        self.comboMarker_Shape.setItemText(7, _translate("MainWindow", "*[star marker]"))
        self.comboMarker_Shape.setItemText(8, _translate("MainWindow", "h[hexagon1 marker]"))
        self.comboMarker_Shape.setItemText(9, _translate("MainWindow", "H[hexagon2 marker]"))
        self.comboMarker_Shape.setItemText(10, _translate("MainWindow", "+[plus marker]"))
        self.comboMarker_Shape.setItemText(11, _translate("MainWindow", "x[x marker]"))
        self.comboMarker_Shape.setItemText(12, _translate("MainWindow", "D[diamond marker]"))
        self.comboMarker_Shape.setItemText(13, _translate("MainWindow", "d[thin_diamond marker]"))
        self.label_17.setText(_translate("MainWindow", "标记点大小"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_Series), _translate("MainWindow", "3. 子图曲线设置"))
        self.groupBox_AxisX.setTitle(_translate("MainWindow", "显示坐标轴X"))
        self.groupBoxX_Lim.setTitle(_translate("MainWindow", "4.1 数据特性"))
        self.label_7.setText(_translate("MainWindow", "最小值"))
        self.label_11.setText(_translate("MainWindow", "最大值"))
        self.btnAxisX_setBound.setText(_translate("MainWindow", "设置范围"))
        self.comboAxisX_Scale.setItemText(0, _translate("MainWindow", "linear"))
        self.comboAxisX_Scale.setItemText(1, _translate("MainWindow", "log"))
        self.comboAxisX_Scale.setItemText(2, _translate("MainWindow", "symlog"))
        self.comboAxisX_Scale.setItemText(3, _translate("MainWindow", "logit"))
        self.label_26.setText(_translate("MainWindow", "坐标尺度"))
        self.chkBoxAxisX_Invert.setText(_translate("MainWindow", "坐标反向"))
        self.groupBox_AxisXLabel.setTitle(_translate("MainWindow", "4.2 X轴标题"))
        self.btnAxisX_setLabel.setText(_translate("MainWindow", "设置轴标题"))
        self.editAxisX_Label.setText(_translate("MainWindow", "time(secs)"))
        self.btnAxisX_LabelColor.setText(_translate("MainWindow", "文字颜色"))
        self.label_19.setText(_translate("MainWindow", "字体大小"))
        self.chkBoxAxisX_LabelBold.setText(_translate("MainWindow", "粗体"))
        self.chkBoxAxisX_LabelItalic.setText(_translate("MainWindow", "斜体"))
        self.groupBoxAxisX_TickLabel.setTitle(_translate("MainWindow", "4.3 主刻度标签"))
        self.btnAxisX_TickLabFormat.setText(_translate("MainWindow", "设置标签格式"))
        self.editAxisX_TickLabFormat.setText(_translate("MainWindow", "%.1f"))
        self.btnAxisX_TickLabColor.setText(_translate("MainWindow", "设置文字颜色"))
        self.label_20.setText(_translate("MainWindow", "字体大小"))
        self.chkBoxAxisX_TickLabBottom.setText(_translate("MainWindow", "下轴"))
        self.chkBoxAxisX_TickLabTop.setText(_translate("MainWindow", "上轴"))
        self.gBoxAxisX_majorTickGrid.setTitle(_translate("MainWindow", "4.4 主刻度线和主网格线"))
        self.chkBoxX_majorTickBottom.setText(_translate("MainWindow", "bottom主刻度线"))
        self.chkBoxX_majorGrid.setText(_translate("MainWindow", "显示主网格线"))
        self.btnLineColorX_majorTick.setText(_translate("MainWindow", "线条颜色"))
        self.chkBoxX_majorTickTop.setText(_translate("MainWindow", "top主刻度线"))
        self.btnLineColorX_majorGrid.setText(_translate("MainWindow", "线条颜色"))
        self.comboLineStyle_XmajorGrid.setItemText(0, _translate("MainWindow", "-"))
        self.comboLineStyle_XmajorGrid.setItemText(1, _translate("MainWindow", "--"))
        self.comboLineStyle_XmajorGrid.setItemText(2, _translate("MainWindow", "-."))
        self.comboLineStyle_XmajorGrid.setItemText(3, _translate("MainWindow", ":"))
        self.comboLineStyle_XmajorGrid.setItemText(4, _translate("MainWindow", "None"))
        self.gBoxAxisX_minorTickGrid.setTitle(_translate("MainWindow", "4.5 次刻度线和次网格线"))
        self.chkBoxX_minorTickBottom.setText(_translate("MainWindow", "bottom次刻度线"))
        self.chkBoxX_minorGrid.setText(_translate("MainWindow", "显示次网格线"))
        self.btnLineColorX_minorTick.setText(_translate("MainWindow", "线条颜色"))
        self.btnLineColorX_minorGrid.setText(_translate("MainWindow", "线条颜色"))
        self.comboLineStyle_XminorGrid.setItemText(0, _translate("MainWindow", "-"))
        self.comboLineStyle_XminorGrid.setItemText(1, _translate("MainWindow", "--"))
        self.comboLineStyle_XminorGrid.setItemText(2, _translate("MainWindow", "-."))
        self.comboLineStyle_XminorGrid.setItemText(3, _translate("MainWindow", ":"))
        self.comboLineStyle_XminorGrid.setItemText(4, _translate("MainWindow", "None"))
        self.chkBoxX_minorTickTop.setText(_translate("MainWindow", "top次刻度线"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_AxisX), _translate("MainWindow", "4. X坐标轴设置"))
        self.groupBox_AxisY.setTitle(_translate("MainWindow", "显示坐标轴Y"))
        self.groupBoxY_Lim.setTitle(_translate("MainWindow", "5.1 数据范围"))
        self.label_9.setText(_translate("MainWindow", "最小值"))
        self.label_21.setText(_translate("MainWindow", "最大值"))
        self.btnAxisY_setBound.setText(_translate("MainWindow", "设置范围"))
        self.comboAxisY_Scale.setItemText(0, _translate("MainWindow", "linear"))
        self.comboAxisY_Scale.setItemText(1, _translate("MainWindow", "log"))
        self.comboAxisY_Scale.setItemText(2, _translate("MainWindow", "symlog"))
        self.comboAxisY_Scale.setItemText(3, _translate("MainWindow", "logit"))
        self.label_27.setText(_translate("MainWindow", "坐标尺度"))
        self.chkBoxAxisY_Invert.setText(_translate("MainWindow", "坐标反向"))
        self.groupBox_AxisYLabel.setTitle(_translate("MainWindow", "5.2 Y轴标题"))
        self.btnAxisY_setLabel.setText(_translate("MainWindow", "设置轴标题"))
        self.editAxisY_Label.setText(_translate("MainWindow", "time(secs)"))
        self.btnAxisY_LabelColor.setText(_translate("MainWindow", "文字颜色"))
        self.label_22.setText(_translate("MainWindow", "字体大小"))
        self.chkBoxAxisY_LabelBold.setText(_translate("MainWindow", "粗体"))
        self.chkBoxAxisY_LabelItalic.setText(_translate("MainWindow", "斜体"))
        self.groupBoxAxisY_TickLabel.setTitle(_translate("MainWindow", "5.3 主刻度标签"))
        self.btnAxisY_TickLabFormat.setText(_translate("MainWindow", "设置标签格式"))
        self.editAxisY_TickLabFormat.setText(_translate("MainWindow", "%.1f"))
        self.btnAxisY_TickLabColor.setText(_translate("MainWindow", "设置文字颜色"))
        self.label_23.setText(_translate("MainWindow", "字体大小"))
        self.chkBoxAxisY_TickLabLeft.setText(_translate("MainWindow", "左轴"))
        self.chkBoxAxisY_TickLabRight.setText(_translate("MainWindow", "右轴"))
        self.gBoxAxisY_majorTickGrid.setTitle(_translate("MainWindow", "5.4 主刻度线和主网格线"))
        self.chkBoxY_majorTickLeft.setText(_translate("MainWindow", "Left主刻度线"))
        self.chkBoxY_majorGrid.setText(_translate("MainWindow", "显示主网格线"))
        self.btnLineColorY_majorTick.setText(_translate("MainWindow", "线条颜色"))
        self.btnLineColorY_majorGrid.setText(_translate("MainWindow", "线条颜色"))
        self.comboLineStyle_YmajorGrid.setItemText(0, _translate("MainWindow", "-"))
        self.comboLineStyle_YmajorGrid.setItemText(1, _translate("MainWindow", "--"))
        self.comboLineStyle_YmajorGrid.setItemText(2, _translate("MainWindow", "-."))
        self.comboLineStyle_YmajorGrid.setItemText(3, _translate("MainWindow", ":"))
        self.comboLineStyle_YmajorGrid.setItemText(4, _translate("MainWindow", "None"))
        self.chkBoxY_majorTickRight.setText(_translate("MainWindow", "Right主刻度线"))
        self.gBoxAxisY_minorTickGrid.setTitle(_translate("MainWindow", "5.5 次刻度线和次网格线"))
        self.chkBoxY_minorTickLeft.setText(_translate("MainWindow", "Left次刻度线"))
        self.chkBoxY_minorGrid.setText(_translate("MainWindow", "显示次网格线"))
        self.btnLineColorY_minorTick.setText(_translate("MainWindow", "线条颜色"))
        self.btnLineColorY_minorGrid.setText(_translate("MainWindow", "线条颜色"))
        self.comboLineStyle_YminorGrid.setItemText(0, _translate("MainWindow", "-"))
        self.comboLineStyle_YminorGrid.setItemText(1, _translate("MainWindow", "--"))
        self.comboLineStyle_YminorGrid.setItemText(2, _translate("MainWindow", "-."))
        self.comboLineStyle_YminorGrid.setItemText(3, _translate("MainWindow", ":"))
        self.comboLineStyle_YminorGrid.setItemText(4, _translate("MainWindow", "None"))
        self.chkBoxY_minorTickRight.setText(_translate("MainWindow", "Right次刻度线"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_AxisY), _translate("MainWindow", "5. Y坐标轴设置"))
        self.actQuit.setText(_translate("MainWindow", "退出"))
        self.actQuit.setToolTip(_translate("MainWindow", "退出"))

import res_rc
