# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(513, 415)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_5.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setContentsMargins(11, 2, 11, 2)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnGetFile = QtWidgets.QPushButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/104.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGetFile.setIcon(icon)
        self.btnGetFile.setObjectName("btnGetFile")
        self.horizontalLayout.addWidget(self.btnGetFile)
        self.editOutputFile = QtWidgets.QLineEdit(self.groupBox_3)
        self.editOutputFile.setObjectName("editOutputFile")
        self.horizontalLayout.addWidget(self.editOutputFile)
        self.LabPassTime = QtWidgets.QLabel(self.groupBox_3)
        self.LabPassTime.setMinimumSize(QtCore.QSize(100, 0))
        self.LabPassTime.setObjectName("LabPassTime")
        self.horizontalLayout.addWidget(self.LabPassTime)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(3, 11, 3, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboDevices = QtWidgets.QComboBox(self.groupBox)
        self.comboDevices.setObjectName("comboDevices")
        self.gridLayout.addWidget(self.comboDevices, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboCodec = QtWidgets.QComboBox(self.groupBox)
        self.comboCodec.setObjectName("comboCodec")
        self.gridLayout.addWidget(self.comboCodec, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboSampleRate = QtWidgets.QComboBox(self.groupBox)
        self.comboSampleRate.setObjectName("comboSampleRate")
        self.gridLayout.addWidget(self.comboSampleRate, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboChannels = QtWidgets.QComboBox(self.groupBox)
        self.comboChannels.setObjectName("comboChannels")
        self.gridLayout.addWidget(self.comboChannels, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBitrate = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBitrate.setObjectName("comboBitrate")
        self.gridLayout_2.addWidget(self.comboBitrate, 1, 1, 1, 1)
        self.radioQuality = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioQuality.setChecked(True)
        self.radioQuality.setObjectName("radioQuality")
        self.gridLayout_2.addWidget(self.radioQuality, 0, 0, 1, 1)
        self.sliderQuality = QtWidgets.QSlider(self.groupBox_2)
        self.sliderQuality.setMaximum(8)
        self.sliderQuality.setOrientation(QtCore.Qt.Horizontal)
        self.sliderQuality.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sliderQuality.setTickInterval(1)
        self.sliderQuality.setObjectName("sliderQuality")
        self.gridLayout_2.addWidget(self.sliderQuality, 0, 1, 1, 1)
        self.radioBitrate = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBitrate.setChecked(False)
        self.radioBitrate.setObjectName("radioBitrate")
        self.gridLayout_2.addWidget(self.radioBitrate, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_5.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setContentsMargins(3, 2, 3, 2)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.spin_byteCount = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_byteCount.setMaximum(999999999)
        self.spin_byteCount.setObjectName("spin_byteCount")
        self.gridLayout_3.addWidget(self.spin_byteCount, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.spin_duration = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_duration.setMaximum(999999999)
        self.spin_duration.setObjectName("spin_duration")
        self.gridLayout_3.addWidget(self.spin_duration, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.spin_frameCount = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_frameCount.setMaximum(999999999)
        self.spin_frameCount.setObjectName("spin_frameCount")
        self.gridLayout_3.addWidget(self.spin_frameCount, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.spin_sampleCount = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_sampleCount.setMaximum(999999999)
        self.spin_sampleCount.setObjectName("spin_sampleCount")
        self.gridLayout_3.addWidget(self.spin_sampleCount, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setVerticalSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        self.spin_channelCount = QtWidgets.QSpinBox(self.groupBox_5)
        self.spin_channelCount.setObjectName("spin_channelCount")
        self.gridLayout_4.addWidget(self.spin_channelCount, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.edit_byteOrder = QtWidgets.QLineEdit(self.groupBox_5)
        self.edit_byteOrder.setObjectName("edit_byteOrder")
        self.gridLayout_4.addWidget(self.edit_byteOrder, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.edit_codec = QtWidgets.QLineEdit(self.groupBox_5)
        self.edit_codec.setObjectName("edit_codec")
        self.gridLayout_4.addWidget(self.edit_codec, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 3, 0, 1, 1)
        self.edit_sampleType = QtWidgets.QLineEdit(self.groupBox_5)
        self.edit_sampleType.setObjectName("edit_sampleType")
        self.gridLayout_4.addWidget(self.edit_sampleType, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 4, 0, 1, 1)
        self.spin_sampleSize = QtWidgets.QSpinBox(self.groupBox_5)
        self.spin_sampleSize.setMaximum(999)
        self.spin_sampleSize.setObjectName("spin_sampleSize")
        self.gridLayout_4.addWidget(self.spin_sampleSize, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 5, 0, 1, 1)
        self.spin_sampleRate = QtWidgets.QSpinBox(self.groupBox_5)
        self.spin_sampleRate.setMaximum(9999999)
        self.spin_sampleRate.setObjectName("spin_sampleRate")
        self.gridLayout_4.addWidget(self.spin_sampleRate, 5, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 6, 0, 1, 1)
        self.spin_bytesPerFrame = QtWidgets.QSpinBox(self.groupBox_5)
        self.spin_bytesPerFrame.setMaximum(999999)
        self.spin_bytesPerFrame.setObjectName("spin_bytesPerFrame")
        self.gridLayout_4.addWidget(self.spin_bytesPerFrame, 6, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.gridLayout_5.addWidget(self.groupBox_4, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 513, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actRecord = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/626.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRecord.setIcon(icon1)
        self.actRecord.setObjectName("actRecord")
        self.actPause = QtWidgets.QAction(MainWindow)
        self.actPause.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/622.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actPause.setIcon(icon2)
        self.actPause.setObjectName("actPause")
        self.actStop = QtWidgets.QAction(MainWindow)
        self.actStop.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/624.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actStop.setIcon(icon3)
        self.actStop.setObjectName("actStop")
        self.actQuit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actQuit.setIcon(icon4)
        self.actQuit.setObjectName("actQuit")
        self.mainToolBar.addAction(self.actRecord)
        self.mainToolBar.addAction(self.actPause)
        self.mainToolBar.addAction(self.actStop)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actQuit)

        self.retranslateUi(MainWindow)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo10_3，QAudioRecorder录制音频"))
        self.btnGetFile.setText(_translate("MainWindow", "录音输出文件"))
        self.LabPassTime.setText(_translate("MainWindow", "已录时间："))
        self.groupBox.setTitle(_translate("MainWindow", "录音设置（QAudioEncoderSettings）"))
        self.label.setText(_translate("MainWindow", "输入设备"))
        self.label_2.setText(_translate("MainWindow", "音频编码"))
        self.label_3.setText(_translate("MainWindow", "采样率"))
        self.label_4.setText(_translate("MainWindow", "通道数"))
        self.groupBox_2.setTitle(_translate("MainWindow", "编码模式"))
        self.radioQuality.setText(_translate("MainWindow", "固定品质"))
        self.radioBitrate.setText(_translate("MainWindow", "固定比特率"))
        self.groupBox_4.setTitle(_translate("MainWindow", "探测QAudioBuffer信息"))
        self.label_6.setText(_translate("MainWindow", "缓冲区字节数"))
        self.spin_byteCount.setSuffix(_translate("MainWindow", "  bytes"))
        self.label_7.setText(_translate("MainWindow", "缓冲区时长(ms)"))
        self.spin_duration.setSuffix(_translate("MainWindow", "  ms"))
        self.label_8.setText(_translate("MainWindow", "缓冲区帧数"))
        self.label_9.setText(_translate("MainWindow", "采样数"))
        self.groupBox_5.setTitle(_translate("MainWindow", "QAudioFormat信息"))
        self.label_10.setText(_translate("MainWindow", "channelCount"))
        self.label_11.setText(_translate("MainWindow", "byteOrder"))
        self.label_12.setText(_translate("MainWindow", "codec"))
        self.label_13.setText(_translate("MainWindow", "sampleType"))
        self.label_14.setText(_translate("MainWindow", "sampleSize"))
        self.spin_sampleSize.setSuffix(_translate("MainWindow", "  bits"))
        self.label_15.setText(_translate("MainWindow", "sampleRate"))
        self.spin_sampleRate.setSuffix(_translate("MainWindow", "  Hz"))
        self.label_16.setText(_translate("MainWindow", "bytesPerFrame"))
        self.spin_bytesPerFrame.setSuffix(_translate("MainWindow", "  bytes"))
        self.actRecord.setText(_translate("MainWindow", "录音"))
        self.actRecord.setToolTip(_translate("MainWindow", "录音"))
        self.actPause.setText(_translate("MainWindow", "暂停"))
        self.actPause.setToolTip(_translate("MainWindow", "暂停"))
        self.actStop.setText(_translate("MainWindow", "停止"))
        self.actStop.setToolTip(_translate("MainWindow", "停止"))
        self.actQuit.setText(_translate("MainWindow", "退出"))
        self.actQuit.setToolTip(_translate("MainWindow", "退出"))

import res_rc
