# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QWDialogData.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QWDialogData(object):
    def setupUi(self, QWDialogData):
        QWDialogData.setObjectName("QWDialogData")
        QWDialogData.resize(499, 324)
        font = QtGui.QFont()
        font.setPointSize(10)
        QWDialogData.setFont(font)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(QWDialogData)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(QWDialogData)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.editName = QtWidgets.QLineEdit(self.groupBox_2)
        self.editName.setObjectName("editName")
        self.gridLayout.addWidget(self.editName, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.comboSex = QtWidgets.QComboBox(self.groupBox_2)
        self.comboSex.setObjectName("comboSex")
        self.comboSex.addItem("")
        self.comboSex.addItem("")
        self.gridLayout.addWidget(self.comboSex, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.editBirth = QtWidgets.QDateEdit(self.groupBox_2)
        self.editBirth.setCalendarPopup(True)
        self.editBirth.setDate(QtCore.QDate(2017, 2, 20))
        self.editBirth.setObjectName("editBirth")
        self.gridLayout.addWidget(self.editBirth, 3, 1, 1, 1)
        self.comboProvince = QtWidgets.QComboBox(self.groupBox_2)
        self.comboProvince.setEditable(True)
        self.comboProvince.setObjectName("comboProvince")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.comboProvince.addItem("")
        self.gridLayout.addWidget(self.comboProvince, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.comboDep = QtWidgets.QComboBox(self.groupBox_2)
        self.comboDep.setEditable(True)
        self.comboDep.setObjectName("comboDep")
        self.comboDep.addItem("")
        self.comboDep.addItem("")
        self.comboDep.addItem("")
        self.comboDep.addItem("")
        self.gridLayout.addWidget(self.comboDep, 5, 1, 1, 1)
        self.spinSalary = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinSalary.setPrefix("")
        self.spinSalary.setMinimum(1000)
        self.spinSalary.setMaximum(50000)
        self.spinSalary.setSingleStep(100)
        self.spinSalary.setProperty("value", 1000)
        self.spinSalary.setObjectName("spinSalary")
        self.gridLayout.addWidget(self.spinSalary, 6, 1, 1, 1)
        self.editMemo = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.editMemo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.editMemo.setObjectName("editMemo")
        self.gridLayout.addWidget(self.editMemo, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinEmpNo = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinEmpNo.setMinimum(1)
        self.spinEmpNo.setMaximum(10000)
        self.spinEmpNo.setObjectName("spinEmpNo")
        self.gridLayout.addWidget(self.spinEmpNo, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.LabPhoto = QtWidgets.QLabel(self.groupBox_2)
        self.LabPhoto.setMinimumSize(QtCore.QSize(150, 0))
        self.LabPhoto.setMaximumSize(QtCore.QSize(350, 16777215))
        self.LabPhoto.setObjectName("LabPhoto")
        self.verticalLayout.addWidget(self.LabPhoto)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.frame = QtWidgets.QFrame(QWDialogData)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnSetPhoto = QtWidgets.QPushButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/00.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSetPhoto.setIcon(icon)
        self.btnSetPhoto.setObjectName("btnSetPhoto")
        self.verticalLayout_2.addWidget(self.btnSetPhoto)
        self.btnClearPhoto = QtWidgets.QPushButton(self.frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/103.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClearPhoto.setIcon(icon1)
        self.btnClearPhoto.setObjectName("btnClearPhoto")
        self.verticalLayout_2.addWidget(self.btnClearPhoto)
        self.btnOK = QtWidgets.QPushButton(self.frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/322.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOK.setIcon(icon2)
        self.btnOK.setObjectName("btnOK")
        self.verticalLayout_2.addWidget(self.btnOK)
        self.btnClose = QtWidgets.QPushButton(self.frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/324.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon3)
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout_2.addWidget(self.btnClose)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.label_12.setBuddy(self.spinSalary)
        self.label_7.setBuddy(self.comboProvince)
        self.label_5.setBuddy(self.editBirth)
        self.label_6.setBuddy(self.comboDep)
        self.label_9.setBuddy(self.editMemo)
        self.label_2.setBuddy(self.editName)
        self.label.setBuddy(self.spinEmpNo)
        self.label_3.setBuddy(self.comboSex)

        self.retranslateUi(QWDialogData)
        self.btnClose.clicked.connect(QWDialogData.reject)
        self.btnOK.clicked.connect(QWDialogData.accept)
        QtCore.QMetaObject.connectSlotsByName(QWDialogData)

    def retranslateUi(self, QWDialogData):
        _translate = QtCore.QCoreApplication.translate
        QWDialogData.setWindowTitle(_translate("QWDialogData", "编辑记录"))
        self.label_12.setText(_translate("QWDialogData", "工  资"))
        self.label_7.setText(_translate("QWDialogData", "出生省份"))
        self.comboSex.setItemText(0, _translate("QWDialogData", "男"))
        self.comboSex.setItemText(1, _translate("QWDialogData", "女"))
        self.label_5.setText(_translate("QWDialogData", "出生日期"))
        self.editBirth.setDisplayFormat(_translate("QWDialogData", "yyyy-MM-dd"))
        self.comboProvince.setCurrentText(_translate("QWDialogData", "北京"))
        self.comboProvince.setItemText(0, _translate("QWDialogData", "北京"))
        self.comboProvince.setItemText(1, _translate("QWDialogData", "上海"))
        self.comboProvince.setItemText(2, _translate("QWDialogData", "天津"))
        self.comboProvince.setItemText(3, _translate("QWDialogData", "重庆"))
        self.comboProvince.setItemText(4, _translate("QWDialogData", "安徽"))
        self.comboProvince.setItemText(5, _translate("QWDialogData", "河北"))
        self.comboProvince.setItemText(6, _translate("QWDialogData", "河南"))
        self.comboProvince.setItemText(7, _translate("QWDialogData", "湖北"))
        self.comboProvince.setItemText(8, _translate("QWDialogData", "湖南"))
        self.comboProvince.setItemText(9, _translate("QWDialogData", "山西"))
        self.comboProvince.setItemText(10, _translate("QWDialogData", "山东"))
        self.comboProvince.setItemText(11, _translate("QWDialogData", "陕西"))
        self.comboProvince.setItemText(12, _translate("QWDialogData", "江苏"))
        self.comboProvince.setItemText(13, _translate("QWDialogData", "江西"))
        self.label_6.setText(_translate("QWDialogData", "部  门"))
        self.comboDep.setCurrentText(_translate("QWDialogData", "销售部"))
        self.comboDep.setItemText(0, _translate("QWDialogData", "销售部"))
        self.comboDep.setItemText(1, _translate("QWDialogData", "技术部"))
        self.comboDep.setItemText(2, _translate("QWDialogData", "生产部"))
        self.comboDep.setItemText(3, _translate("QWDialogData", "行政部"))
        self.label_9.setText(_translate("QWDialogData", "备   注"))
        self.label_2.setText(_translate("QWDialogData", "姓  名"))
        self.label.setText(_translate("QWDialogData", "工  号"))
        self.label_3.setText(_translate("QWDialogData", "性  别"))
        self.label_13.setText(_translate("QWDialogData", "照  片"))
        self.LabPhoto.setText(_translate("QWDialogData", "LabPhoto"))
        self.btnSetPhoto.setText(_translate("QWDialogData", "导入照片"))
        self.btnClearPhoto.setText(_translate("QWDialogData", "清除照片"))
        self.btnOK.setText(_translate("QWDialogData", "确  定"))
        self.btnClose.setText(_translate("QWDialogData", "取  消"))

import res_rc
