# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 340)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(11, 5, 11, 5)
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboCamera = QtWidgets.QComboBox(self.groupBox_2)
        self.comboCamera.setMinimumSize(QtCore.QSize(150, 20))
        self.comboCamera.setObjectName("comboCamera")
        self.gridLayout.addWidget(self.comboCamera, 0, 1, 1, 1)
        self.checkStillImage = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkStillImage.setEnabled(False)
        self.checkStillImage.setObjectName("checkStillImage")
        self.gridLayout.addWidget(self.checkStillImage, 0, 2, 1, 1)
        self.checkVideo = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkVideo.setEnabled(False)
        self.checkVideo.setObjectName("checkVideo")
        self.gridLayout.addWidget(self.checkVideo, 0, 3, 1, 1)
        self.chkBoxSaveToFile = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkBoxSaveToFile.setChecked(True)
        self.chkBoxSaveToFile.setObjectName("chkBoxSaveToFile")
        self.gridLayout.addWidget(self.chkBoxSaveToFile, 1, 1, 1, 1)
        self.checkFocus = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkFocus.setEnabled(False)
        self.checkFocus.setObjectName("checkFocus")
        self.gridLayout.addWidget(self.checkFocus, 1, 2, 1, 1)
        self.checkExposure = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkExposure.setEnabled(False)
        self.checkExposure.setObjectName("checkExposure")
        self.gridLayout.addWidget(self.checkExposure, 1, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.viewFinder = QCameraViewfinder(self.groupBox)
        self.viewFinder.setMinimumSize(QtCore.QSize(150, 0))
        self.viewFinder.setObjectName("viewFinder")
        self.verticalLayout.addWidget(self.viewFinder)
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LabImage = QtWidgets.QLabel(self.groupBox_3)
        self.LabImage.setAlignment(QtCore.Qt.AlignCenter)
        self.LabImage.setObjectName("LabImage")
        self.verticalLayout_2.addWidget(self.LabImage)
        self.verticalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 541, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actStartCamera = QtWidgets.QAction(MainWindow)
        self.actStartCamera.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/video_chat.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actStartCamera.setIcon(icon)
        self.actStartCamera.setObjectName("actStartCamera")
        self.actStopCamera = QtWidgets.QAction(MainWindow)
        self.actStopCamera.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/remove_user.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actStopCamera.setIcon(icon1)
        self.actStopCamera.setObjectName("actStopCamera")
        self.actCapture = QtWidgets.QAction(MainWindow)
        self.actCapture.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/picture.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actCapture.setIcon(icon2)
        self.actCapture.setObjectName("actCapture")
        self.actQuit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/exit_24.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actQuit.setIcon(icon3)
        self.actQuit.setObjectName("actQuit")
        self.mainToolBar.addAction(self.actStartCamera)
        self.mainToolBar.addAction(self.actStopCamera)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actCapture)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actQuit)

        self.retranslateUi(MainWindow)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo10_7, Camera拍照"))
        self.label.setText(_translate("MainWindow", "摄像头设备"))
        self.checkStillImage.setText(_translate("MainWindow", "支持拍照"))
        self.checkVideo.setText(_translate("MainWindow", "支持录像"))
        self.chkBoxSaveToFile.setText(_translate("MainWindow", "图片保存到文件"))
        self.checkFocus.setText(_translate("MainWindow", "支持变焦"))
        self.checkExposure.setText(_translate("MainWindow", "支持曝光控制"))
        self.groupBox.setTitle(_translate("MainWindow", "摄像头预览"))
        self.groupBox_3.setTitle(_translate("MainWindow", "抓取的图片"))
        self.LabImage.setText(_translate("MainWindow", "抓取的图片"))
        self.actStartCamera.setText(_translate("MainWindow", "开启摄像头"))
        self.actStartCamera.setToolTip(_translate("MainWindow", "开启摄像头"))
        self.actStopCamera.setText(_translate("MainWindow", "关闭摄像头"))
        self.actStopCamera.setToolTip(_translate("MainWindow", "关闭摄像头"))
        self.actCapture.setText(_translate("MainWindow", "摄像头拍照"))
        self.actCapture.setToolTip(_translate("MainWindow", "摄像头拍照"))
        self.actQuit.setText(_translate("MainWindow", "退出"))
        self.actQuit.setToolTip(_translate("MainWindow", "退出"))

from PyQt5.QtMultimediaWidgets import QCameraViewfinder
import res_rc
