# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(712, 502)
        font = QtGui.QFont()
        font.setPointSize(10)
        Widget.setFont(font)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(Widget)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radio_Source = QtWidgets.QRadioButton(self.groupBox_6)
        self.radio_Source.setChecked(True)
        self.radio_Source.setObjectName("radio_Source")
        self.verticalLayout_5.addWidget(self.radio_Source)
        self.radio_List = QtWidgets.QRadioButton(self.groupBox_6)
        self.radio_List.setObjectName("radio_List")
        self.verticalLayout_5.addWidget(self.radio_List)
        self.radio_Tree = QtWidgets.QRadioButton(self.groupBox_6)
        self.radio_Tree.setObjectName("radio_Tree")
        self.verticalLayout_5.addWidget(self.radio_Tree)
        self.radio_Table = QtWidgets.QRadioButton(self.groupBox_6)
        self.radio_Table.setObjectName("radio_Table")
        self.verticalLayout_5.addWidget(self.radio_Table)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.chkBox_AcceptDrops = QtWidgets.QCheckBox(self.groupBox_5)
        self.chkBox_AcceptDrops.setObjectName("chkBox_AcceptDrops")
        self.gridLayout.addWidget(self.chkBox_AcceptDrops, 0, 0, 1, 1)
        self.chkBox_DragEnabled = QtWidgets.QCheckBox(self.groupBox_5)
        self.chkBox_DragEnabled.setObjectName("chkBox_DragEnabled")
        self.gridLayout.addWidget(self.chkBox_DragEnabled, 0, 1, 1, 1)
        self.combo_DefaultAction = QtWidgets.QComboBox(self.groupBox_5)
        self.combo_DefaultAction.setObjectName("combo_DefaultAction")
        self.combo_DefaultAction.addItem("")
        self.combo_DefaultAction.addItem("")
        self.combo_DefaultAction.addItem("")
        self.combo_DefaultAction.addItem("")
        self.gridLayout.addWidget(self.combo_DefaultAction, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.combo_Mode = QtWidgets.QComboBox(self.groupBox_5)
        self.combo_Mode.setMinimumSize(QtCore.QSize(120, 0))
        self.combo_Mode.setObjectName("combo_Mode")
        self.combo_Mode.addItem("")
        self.combo_Mode.addItem("")
        self.combo_Mode.addItem("")
        self.combo_Mode.addItem("")
        self.combo_Mode.addItem("")
        self.gridLayout.addWidget(self.combo_Mode, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_1 = QtWidgets.QGroupBox(Widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_1.setFont(font)
        self.groupBox_1.setFlat(False)
        self.groupBox_1.setCheckable(False)
        self.groupBox_1.setObjectName("groupBox_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_1)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listSource = QtWidgets.QListWidget(self.groupBox_1)
        self.listSource.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listSource.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.listSource.setAlternatingRowColors(True)
        self.listSource.setUniformItemSizes(False)
        self.listSource.setSelectionRectVisible(True)
        self.listSource.setObjectName("listSource")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/200.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/202.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/204.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/500.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/502.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/504.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/508.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/510.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/512.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon8)
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/718.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon9)
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/images/724.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon10)
        self.listSource.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/images/728.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon11)
        self.listSource.addItem(item)
        self.verticalLayout_2.addWidget(self.listSource)
        self.horizontalLayout_2.addWidget(self.groupBox_1)
        self.groupBox_2 = QtWidgets.QGroupBox(Widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox_3)
        self.treeWidget.setAcceptDrops(True)
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeWidget.setDragDropOverwriteMode(True)
        self.treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.treeWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setVisible(False)
        self.verticalLayout_3.addWidget(self.treeWidget)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Widget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget.setMinimumSize(QtCore.QSize(180, 0))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setRowCount(6)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(75)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Demo5_6, 具有DragDrop功能的组件"))
        self.groupBox_6.setTitle(_translate("Widget", "设置对象"))
        self.radio_Source.setText(_translate("Widget", "listSource"))
        self.radio_List.setText(_translate("Widget", "listWidget"))
        self.radio_Tree.setText(_translate("Widget", "treeWidget"))
        self.radio_Table.setText(_translate("Widget", "tableWidget"))
        self.groupBox_5.setTitle(_translate("Widget", "拖放参数设置"))
        self.label_2.setText(_translate("Widget", "dragDropMode"))
        self.chkBox_AcceptDrops.setText(_translate("Widget", "acceptDrops"))
        self.chkBox_DragEnabled.setText(_translate("Widget", "dragEnabled"))
        self.combo_DefaultAction.setItemText(0, _translate("Widget", "CopyAction"))
        self.combo_DefaultAction.setItemText(1, _translate("Widget", "MoveAction"))
        self.combo_DefaultAction.setItemText(2, _translate("Widget", "LinkAction"))
        self.combo_DefaultAction.setItemText(3, _translate("Widget", "IgnoreAction"))
        self.label_3.setText(_translate("Widget", "defaultDropAction"))
        self.combo_Mode.setItemText(0, _translate("Widget", "NoDragDrop"))
        self.combo_Mode.setItemText(1, _translate("Widget", "DragOnly"))
        self.combo_Mode.setItemText(2, _translate("Widget", "DropOnly"))
        self.combo_Mode.setItemText(3, _translate("Widget", "DragDrop"))
        self.combo_Mode.setItemText(4, _translate("Widget", "InternalMove"))
        self.groupBox_1.setTitle(_translate("Widget", "listSource"))
        __sortingEnabled = self.listSource.isSortingEnabled()
        self.listSource.setSortingEnabled(False)
        item = self.listSource.item(0)
        item.setText(_translate("Widget", "剪切"))
        item = self.listSource.item(1)
        item.setText(_translate("Widget", "复制"))
        item = self.listSource.item(2)
        item.setText(_translate("Widget", "粘贴"))
        item = self.listSource.item(3)
        item.setText(_translate("Widget", "粗体"))
        item = self.listSource.item(4)
        item.setText(_translate("Widget", "斜体"))
        item = self.listSource.item(5)
        item.setText(_translate("Widget", "下划线"))
        item = self.listSource.item(6)
        item.setText(_translate("Widget", "左对齐"))
        item = self.listSource.item(7)
        item.setText(_translate("Widget", "中间对齐"))
        item = self.listSource.item(8)
        item.setText(_translate("Widget", "右对齐"))
        item = self.listSource.item(9)
        item.setText(_translate("Widget", "红色"))
        item = self.listSource.item(10)
        item.setText(_translate("Widget", "绿色"))
        item = self.listSource.item(11)
        item.setText(_translate("Widget", "蓝色"))
        self.listSource.setSortingEnabled(__sortingEnabled)
        self.groupBox_2.setTitle(_translate("Widget", "listWidget"))
        self.groupBox_3.setTitle(_translate("Widget", "treeWidget"))
        self.treeWidget.headerItem().setText(0, _translate("Widget", "编辑"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Widget", "编辑"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Widget", "格式"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_4.setTitle(_translate("Widget", "tableWidget"))

import res_rc
