# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(949, 610)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setGeometry(QtCore.QRect(0, 40, 881, 445))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBoxSort = QtWidgets.QGroupBox(self.frame)
        self.groupBoxSort.setEnabled(False)
        self.groupBoxSort.setObjectName("groupBoxSort")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxSort)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.groupBoxSort)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.comboFields = QtWidgets.QComboBox(self.groupBoxSort)
        self.comboFields.setObjectName("comboFields")
        self.gridLayout_3.addWidget(self.comboFields, 0, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.radioBtnAscend = QtWidgets.QRadioButton(self.groupBoxSort)
        self.radioBtnAscend.setChecked(True)
        self.radioBtnAscend.setObjectName("radioBtnAscend")
        self.gridLayout_3.addWidget(self.radioBtnAscend, 1, 1, 1, 1)
        self.radioBtnDescend = QtWidgets.QRadioButton(self.groupBoxSort)
        self.radioBtnDescend.setObjectName("radioBtnDescend")
        self.gridLayout_3.addWidget(self.radioBtnDescend, 1, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBoxSort)
        self.groupBoxFilter = QtWidgets.QGroupBox(self.frame)
        self.groupBoxFilter.setEnabled(False)
        self.groupBoxFilter.setObjectName("groupBoxFilter")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxFilter)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioBtnMan = QtWidgets.QRadioButton(self.groupBoxFilter)
        self.radioBtnMan.setObjectName("radioBtnMan")
        self.gridLayout_2.addWidget(self.radioBtnMan, 0, 0, 1, 1)
        self.radioBtnWoman = QtWidgets.QRadioButton(self.groupBoxFilter)
        self.radioBtnWoman.setObjectName("radioBtnWoman")
        self.gridLayout_2.addWidget(self.radioBtnWoman, 0, 1, 1, 1)
        self.radioBtnBoth = QtWidgets.QRadioButton(self.groupBoxFilter)
        self.radioBtnBoth.setChecked(True)
        self.radioBtnBoth.setObjectName("radioBtnBoth")
        self.gridLayout_2.addWidget(self.radioBtnBoth, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBoxFilter)
        spacerItem2 = QtWidgets.QSpacerItem(17, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.frame)
        self.tableView = QtWidgets.QTableView(self.groupBox_3)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(50)
        self.verticalLayout_2.addWidget(self.tableView)
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.dbComboSex = QtWidgets.QComboBox(self.groupBox)
        self.dbComboSex.setObjectName("dbComboSex")
        self.dbComboSex.addItem("")
        self.dbComboSex.addItem("")
        self.gridLayout.addWidget(self.dbComboSex, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.dbEditName = QtWidgets.QLineEdit(self.groupBox)
        self.dbEditName.setObjectName("dbEditName")
        self.gridLayout.addWidget(self.dbEditName, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.dbSpinSalary = QtWidgets.QSpinBox(self.groupBox)
        self.dbSpinSalary.setPrefix("")
        self.dbSpinSalary.setMinimum(1000)
        self.dbSpinSalary.setMaximum(50000)
        self.dbSpinSalary.setSingleStep(100)
        self.dbSpinSalary.setProperty("value", 1000)
        self.dbSpinSalary.setObjectName("dbSpinSalary")
        self.gridLayout.addWidget(self.dbSpinSalary, 6, 1, 1, 1)
        self.dbEditMemo = QtWidgets.QPlainTextEdit(self.groupBox)
        self.dbEditMemo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dbEditMemo.setObjectName("dbEditMemo")
        self.gridLayout.addWidget(self.dbEditMemo, 7, 1, 1, 1)
        self.dbComboDep = QtWidgets.QComboBox(self.groupBox)
        self.dbComboDep.setEditable(True)
        self.dbComboDep.setObjectName("dbComboDep")
        self.dbComboDep.addItem("")
        self.dbComboDep.addItem("")
        self.dbComboDep.addItem("")
        self.dbComboDep.addItem("")
        self.gridLayout.addWidget(self.dbComboDep, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.dbSpinEmpNo = QtWidgets.QSpinBox(self.groupBox)
        self.dbSpinEmpNo.setMinimum(1)
        self.dbSpinEmpNo.setMaximum(10000)
        self.dbSpinEmpNo.setObjectName("dbSpinEmpNo")
        self.gridLayout.addWidget(self.dbSpinEmpNo, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.dbComboProvince = QtWidgets.QComboBox(self.groupBox)
        self.dbComboProvince.setEditable(True)
        self.dbComboProvince.setObjectName("dbComboProvince")
        self.dbComboProvince.addItem("")
        self.dbComboProvince.addItem("")
        self.dbComboProvince.addItem("")
        self.dbComboProvince.addItem("")
        self.dbComboProvince.addItem("")
        self.dbComboProvince.addItem("")
        self.dbComboProvince.addItem("")
        self.dbComboProvince.addItem("")
        self.dbComboProvince.addItem("")
        self.dbComboProvince.addItem("")
        self.dbComboProvince.addItem("")
        self.dbComboProvince.addItem("")
        self.dbComboProvince.addItem("")
        self.dbComboProvince.addItem("")
        self.gridLayout.addWidget(self.dbComboProvince, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.dbEditBirth = QtWidgets.QDateEdit(self.groupBox)
        self.dbEditBirth.setCalendarPopup(True)
        self.dbEditBirth.setDate(QtCore.QDate(2017, 2, 20))
        self.dbEditBirth.setObjectName("dbEditBirth")
        self.gridLayout.addWidget(self.dbEditBirth, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.dbLabPhoto = QtWidgets.QLabel(self.groupBox)
        self.dbLabPhoto.setMinimumSize(QtCore.QSize(150, 0))
        self.dbLabPhoto.setMaximumSize(QtCore.QSize(400, 16777215))
        self.dbLabPhoto.setObjectName("dbLabPhoto")
        self.verticalLayout.addWidget(self.dbLabPhoto)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 949, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setIconSize(QtCore.QSize(16, 16))
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actOpenDB = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/open3.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actOpenDB.setIcon(icon)
        self.actOpenDB.setObjectName("actOpenDB")
        self.actQuit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/exit.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actQuit.setIcon(icon1)
        self.actQuit.setObjectName("actQuit")
        self.actRecAppend = QtWidgets.QAction(MainWindow)
        self.actRecAppend.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/316.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRecAppend.setIcon(icon2)
        self.actRecAppend.setObjectName("actRecAppend")
        self.actRecInsert = QtWidgets.QAction(MainWindow)
        self.actRecInsert.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/306.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRecInsert.setIcon(icon3)
        self.actRecInsert.setObjectName("actRecInsert")
        self.actSubmit = QtWidgets.QAction(MainWindow)
        self.actSubmit.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/save1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSubmit.setIcon(icon4)
        self.actSubmit.setObjectName("actSubmit")
        self.actRevert = QtWidgets.QAction(MainWindow)
        self.actRevert.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/ubdo.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRevert.setIcon(icon5)
        self.actRevert.setObjectName("actRevert")
        self.actRecDelete = QtWidgets.QAction(MainWindow)
        self.actRecDelete.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/delete1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRecDelete.setIcon(icon6)
        self.actRecDelete.setObjectName("actRecDelete")
        self.actPhoto = QtWidgets.QAction(MainWindow)
        self.actPhoto.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/00.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actPhoto.setIcon(icon7)
        self.actPhoto.setObjectName("actPhoto")
        self.actPhotoClear = QtWidgets.QAction(MainWindow)
        self.actPhotoClear.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/103.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actPhotoClear.setIcon(icon8)
        self.actPhotoClear.setObjectName("actPhotoClear")
        self.actScan = QtWidgets.QAction(MainWindow)
        self.actScan.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/up.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actScan.setIcon(icon9)
        self.actScan.setObjectName("actScan")
        self.mainToolBar.addAction(self.actOpenDB)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actRecAppend)
        self.mainToolBar.addAction(self.actRecInsert)
        self.mainToolBar.addAction(self.actRecDelete)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actPhoto)
        self.mainToolBar.addAction(self.actPhotoClear)
        self.mainToolBar.addAction(self.actScan)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actSubmit)
        self.mainToolBar.addAction(self.actRevert)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actQuit)
        self.label_2.setBuddy(self.dbEditName)
        self.label_3.setBuddy(self.dbComboSex)
        self.label_9.setBuddy(self.dbEditMemo)
        self.label_12.setBuddy(self.dbSpinSalary)
        self.label_6.setBuddy(self.dbComboDep)
        self.label.setBuddy(self.dbSpinEmpNo)
        self.label_7.setBuddy(self.dbComboProvince)
        self.label_5.setBuddy(self.dbEditBirth)

        self.retranslateUi(MainWindow)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo7_1, QSqlTableModel的使用"))
        self.groupBoxSort.setTitle(_translate("MainWindow", "排序"))
        self.label_14.setText(_translate("MainWindow", "排序字段"))
        self.radioBtnAscend.setText(_translate("MainWindow", "升序"))
        self.radioBtnDescend.setText(_translate("MainWindow", "降序"))
        self.groupBoxFilter.setTitle(_translate("MainWindow", "数据过滤"))
        self.radioBtnMan.setText(_translate("MainWindow", "男"))
        self.radioBtnWoman.setText(_translate("MainWindow", "女"))
        self.radioBtnBoth.setText(_translate("MainWindow", "全显示"))
        self.label_2.setText(_translate("MainWindow", "姓  名"))
        self.dbComboSex.setItemText(0, _translate("MainWindow", "男"))
        self.dbComboSex.setItemText(1, _translate("MainWindow", "女"))
        self.label_3.setText(_translate("MainWindow", "性  别"))
        self.label_9.setText(_translate("MainWindow", "备   注"))
        self.label_12.setText(_translate("MainWindow", "工  资"))
        self.dbComboDep.setItemText(0, _translate("MainWindow", "销售部"))
        self.dbComboDep.setItemText(1, _translate("MainWindow", "技术部"))
        self.dbComboDep.setItemText(2, _translate("MainWindow", "生产部"))
        self.dbComboDep.setItemText(3, _translate("MainWindow", "行政部"))
        self.label_6.setText(_translate("MainWindow", "部  门"))
        self.label.setText(_translate("MainWindow", "工  号"))
        self.label_7.setText(_translate("MainWindow", "出生省份"))
        self.dbComboProvince.setItemText(0, _translate("MainWindow", "北京"))
        self.dbComboProvince.setItemText(1, _translate("MainWindow", "上海"))
        self.dbComboProvince.setItemText(2, _translate("MainWindow", "天津"))
        self.dbComboProvince.setItemText(3, _translate("MainWindow", "重庆"))
        self.dbComboProvince.setItemText(4, _translate("MainWindow", "安徽"))
        self.dbComboProvince.setItemText(5, _translate("MainWindow", "河北"))
        self.dbComboProvince.setItemText(6, _translate("MainWindow", "河南"))
        self.dbComboProvince.setItemText(7, _translate("MainWindow", "湖北"))
        self.dbComboProvince.setItemText(8, _translate("MainWindow", "湖南"))
        self.dbComboProvince.setItemText(9, _translate("MainWindow", "山西"))
        self.dbComboProvince.setItemText(10, _translate("MainWindow", "山东"))
        self.dbComboProvince.setItemText(11, _translate("MainWindow", "陕西"))
        self.dbComboProvince.setItemText(12, _translate("MainWindow", "江苏"))
        self.dbComboProvince.setItemText(13, _translate("MainWindow", "江西"))
        self.label_5.setText(_translate("MainWindow", "出生日期"))
        self.dbEditBirth.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_13.setText(_translate("MainWindow", "照  片"))
        self.dbLabPhoto.setText(_translate("MainWindow", "dbLabPhoto"))
        self.actOpenDB.setText(_translate("MainWindow", "打开"))
        self.actOpenDB.setToolTip(_translate("MainWindow", "打开数据库"))
        self.actQuit.setText(_translate("MainWindow", "退出"))
        self.actQuit.setToolTip(_translate("MainWindow", "退出"))
        self.actRecAppend.setText(_translate("MainWindow", "添加"))
        self.actRecAppend.setToolTip(_translate("MainWindow", "添加记录"))
        self.actRecInsert.setText(_translate("MainWindow", "插入"))
        self.actRecInsert.setToolTip(_translate("MainWindow", "插入记录"))
        self.actSubmit.setText(_translate("MainWindow", "保存"))
        self.actSubmit.setToolTip(_translate("MainWindow", "保存修改"))
        self.actRevert.setText(_translate("MainWindow", "取消"))
        self.actRevert.setToolTip(_translate("MainWindow", "取消修改"))
        self.actRecDelete.setText(_translate("MainWindow", "删除"))
        self.actRecDelete.setToolTip(_translate("MainWindow", "删除记录"))
        self.actPhoto.setText(_translate("MainWindow", "设置照片"))
        self.actPhoto.setToolTip(_translate("MainWindow", "设置照片"))
        self.actPhotoClear.setText(_translate("MainWindow", "清除照片"))
        self.actPhotoClear.setToolTip(_translate("MainWindow", "清除照片"))
        self.actScan.setText(_translate("MainWindow", "涨工资"))
        self.actScan.setToolTip(_translate("MainWindow", "涨工资"))

import res_rc
