# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 473)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frameSetup = QtWidgets.QFrame(self.splitter)
        self.frameSetup.setEnabled(False)
        self.frameSetup.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frameSetup.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameSetup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSetup.setObjectName("frameSetup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameSetup)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frameSetup)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.radioFill_Pos = QtWidgets.QRadioButton(self.groupBox)
        self.radioFill_Pos.setChecked(True)
        self.radioFill_Pos.setObjectName("radioFill_Pos")
        self.gridLayout.addWidget(self.radioFill_Pos, 0, 0, 1, 1)
        self.radioFill_Neg = QtWidgets.QRadioButton(self.groupBox)
        self.radioFill_Neg.setChecked(False)
        self.radioFill_Neg.setObjectName("radioFill_Neg")
        self.gridLayout.addWidget(self.radioFill_Neg, 0, 1, 1, 1)
        self.radioFill_Both = QtWidgets.QRadioButton(self.groupBox)
        self.radioFill_Both.setChecked(False)
        self.radioFill_Both.setObjectName("radioFill_Both")
        self.gridLayout.addWidget(self.radioFill_Both, 1, 0, 1, 1)
        self.radioFill_None = QtWidgets.QRadioButton(self.groupBox)
        self.radioFill_None.setObjectName("radioFill_None")
        self.gridLayout.addWidget(self.radioFill_None, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frameSetup)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinY_Min = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinY_Min.setMinimum(-50000.0)
        self.spinY_Min.setMaximum(50000.0)
        self.spinY_Min.setProperty("value", -5.0)
        self.spinY_Min.setObjectName("spinY_Min")
        self.gridLayout_3.addWidget(self.spinY_Min, 0, 1, 1, 1)
        self.btnY_SetRange = QtWidgets.QPushButton(self.groupBox_3)
        self.btnY_SetRange.setObjectName("btnY_SetRange")
        self.gridLayout_3.addWidget(self.btnY_SetRange, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.spinY_Max = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinY_Max.setMaximum(1000000.0)
        self.spinY_Max.setProperty("value", 5.0)
        self.spinY_Max.setObjectName("spinY_Max")
        self.gridLayout_3.addWidget(self.spinY_Max, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinY_Ticks = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinY_Ticks.setMinimum(3)
        self.spinY_Ticks.setMaximum(1000)
        self.spinY_Ticks.setProperty("value", 5)
        self.spinY_Ticks.setDisplayIntegerBase(10)
        self.spinY_Ticks.setObjectName("spinY_Ticks")
        self.gridLayout_3.addWidget(self.spinY_Ticks, 2, 1, 1, 1)
        self.chkBoxY_GridLine = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkBoxY_GridLine.setChecked(True)
        self.chkBoxY_GridLine.setObjectName("chkBoxY_GridLine")
        self.gridLayout_3.addWidget(self.chkBoxY_GridLine, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frameSetup)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setVerticalSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.spinX_Min = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spinX_Min.setMinimum(-50000.0)
        self.spinX_Min.setMaximum(50000.0)
        self.spinX_Min.setProperty("value", 0.0)
        self.spinX_Min.setObjectName("spinX_Min")
        self.gridLayout_4.addWidget(self.spinX_Min, 0, 1, 1, 1)
        self.btnX_SetRange = QtWidgets.QPushButton(self.groupBox_4)
        self.btnX_SetRange.setObjectName("btnX_SetRange")
        self.gridLayout_4.addWidget(self.btnX_SetRange, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.spinX_Max = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spinX_Max.setMaximum(1000000.0)
        self.spinX_Max.setProperty("value", 5.0)
        self.spinX_Max.setObjectName("spinX_Max")
        self.gridLayout_4.addWidget(self.spinX_Max, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.spinX_Ticks = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinX_Ticks.setMinimum(3)
        self.spinX_Ticks.setMaximum(1000)
        self.spinX_Ticks.setProperty("value", 5)
        self.spinX_Ticks.setDisplayIntegerBase(10)
        self.spinX_Ticks.setObjectName("spinX_Ticks")
        self.gridLayout_4.addWidget(self.spinX_Ticks, 2, 1, 1, 1)
        self.chkBoxX_GridLine = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkBoxX_GridLine.setChecked(True)
        self.chkBoxX_GridLine.setObjectName("chkBoxX_GridLine")
        self.gridLayout_4.addWidget(self.chkBoxX_GridLine, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_chart = QtWidgets.QFrame(self.splitter)
        self.frame_chart.setObjectName("frame_chart")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_chart)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chartView = QmyChartView(self.frame_chart)
        self.chartView.setObjectName("chartView")
        self.verticalLayout.addWidget(self.chartView)
        self.verticalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 814, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actZoomReset = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/414.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomReset.setIcon(icon)
        self.actZoomReset.setObjectName("actZoomReset")
        self.actQuit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actQuit.setIcon(icon1)
        self.actQuit.setObjectName("actQuit")
        self.actZoomIn = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/418.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomIn.setIcon(icon2)
        self.actZoomIn.setObjectName("actZoomIn")
        self.actZoomOut = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/416.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomOut.setIcon(icon3)
        self.actZoomOut.setObjectName("actZoomOut")
        self.actOpen = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/001.GIF"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actOpen.setIcon(icon4)
        self.actOpen.setObjectName("actOpen")
        self.mainToolBar.addAction(self.actOpen)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actZoomIn)
        self.mainToolBar.addAction(self.actZoomOut)
        self.mainToolBar.addAction(self.actZoomReset)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actQuit)

        self.retranslateUi(MainWindow)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radioFill_Pos, self.radioFill_Neg)
        MainWindow.setTabOrder(self.radioFill_Neg, self.radioFill_Both)
        MainWindow.setTabOrder(self.radioFill_Both, self.radioFill_None)
        MainWindow.setTabOrder(self.radioFill_None, self.spinY_Min)
        MainWindow.setTabOrder(self.spinY_Min, self.spinY_Max)
        MainWindow.setTabOrder(self.spinY_Max, self.btnY_SetRange)
        MainWindow.setTabOrder(self.btnY_SetRange, self.spinY_Ticks)
        MainWindow.setTabOrder(self.spinY_Ticks, self.chkBoxY_GridLine)
        MainWindow.setTabOrder(self.chkBoxY_GridLine, self.spinX_Min)
        MainWindow.setTabOrder(self.spinX_Min, self.spinX_Max)
        MainWindow.setTabOrder(self.spinX_Max, self.btnX_SetRange)
        MainWindow.setTabOrder(self.btnX_SetRange, self.spinX_Ticks)
        MainWindow.setTabOrder(self.spinX_Ticks, self.chkBoxX_GridLine)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "面积填充图"))
        self.groupBox.setTitle(_translate("MainWindow", "填充类型"))
        self.radioFill_Pos.setText(_translate("MainWindow", "正半部分填充"))
        self.radioFill_Neg.setText(_translate("MainWindow", "负半部分填充"))
        self.radioFill_Both.setText(_translate("MainWindow", "正、负均填充"))
        self.radioFill_None.setText(_translate("MainWindow", "不填充"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Y轴--QValueAxis"))
        self.label_5.setText(_translate("MainWindow", "最小值"))
        self.btnY_SetRange.setText(_translate("MainWindow", "设置范围"))
        self.label_6.setText(_translate("MainWindow", "最大值"))
        self.label_3.setText(_translate("MainWindow", "分度个数"))
        self.chkBoxY_GridLine.setText(_translate("MainWindow", "显示网格线"))
        self.groupBox_4.setTitle(_translate("MainWindow", "X轴--QValueAxis"))
        self.label_7.setText(_translate("MainWindow", "最小值"))
        self.btnX_SetRange.setText(_translate("MainWindow", "设置范围"))
        self.label_8.setText(_translate("MainWindow", "最大值"))
        self.label_4.setText(_translate("MainWindow", "分度个数"))
        self.chkBoxX_GridLine.setText(_translate("MainWindow", "显示网格线"))
        self.actZoomReset.setText(_translate("MainWindow", "原始大小"))
        self.actZoomReset.setToolTip(_translate("MainWindow", "原始大小"))
        self.actQuit.setText(_translate("MainWindow", "退出"))
        self.actQuit.setToolTip(_translate("MainWindow", "退出"))
        self.actZoomIn.setText(_translate("MainWindow", "放大"))
        self.actZoomIn.setToolTip(_translate("MainWindow", "放大"))
        self.actZoomOut.setText(_translate("MainWindow", "缩小"))
        self.actZoomOut.setToolTip(_translate("MainWindow", "缩小"))
        self.actOpen.setText(_translate("MainWindow", "打开文件"))
        self.actOpen.setToolTip(_translate("MainWindow", "打开数据文件"))

from myChartView import QmyChartView
import res_rc
