# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 403)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setGeometry(QtCore.QRect(100, 40, 532, 261))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(self.groupBox)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 753, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/open.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actOpen.setIcon(icon)
        self.actOpen.setObjectName("actOpen")
        self.actSave = QtWidgets.QAction(MainWindow)
        self.actSave.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/save.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSave.setIcon(icon1)
        self.actSave.setObjectName("actSave")
        self.actAppend = QtWidgets.QAction(MainWindow)
        self.actAppend.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/append.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actAppend.setIcon(icon2)
        self.actAppend.setObjectName("actAppend")
        self.actInsert = QtWidgets.QAction(MainWindow)
        self.actInsert.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/306.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actInsert.setIcon(icon3)
        self.actInsert.setObjectName("actInsert")
        self.actDelete = QtWidgets.QAction(MainWindow)
        self.actDelete.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/delete.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actDelete.setIcon(icon4)
        self.actDelete.setObjectName("actDelete")
        self.actExit = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actExit.setIcon(icon5)
        self.actExit.setObjectName("actExit")
        self.actModelData = QtWidgets.QAction(MainWindow)
        self.actModelData.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/export1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actModelData.setIcon(icon6)
        self.actModelData.setObjectName("actModelData")
        self.actAlignLeft = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/508.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actAlignLeft.setIcon(icon7)
        self.actAlignLeft.setObjectName("actAlignLeft")
        self.actAlignCenter = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/510.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actAlignCenter.setIcon(icon8)
        self.actAlignCenter.setObjectName("actAlignCenter")
        self.actAlignRight = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/512.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actAlignRight.setIcon(icon9)
        self.actAlignRight.setObjectName("actAlignRight")
        self.actFontBold = QtWidgets.QAction(MainWindow)
        self.actFontBold.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/images/500.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFontBold.setIcon(icon10)
        self.actFontBold.setObjectName("actFontBold")
        self.mainToolBar.addAction(self.actOpen)
        self.mainToolBar.addAction(self.actSave)
        self.mainToolBar.addAction(self.actModelData)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actAppend)
        self.mainToolBar.addAction(self.actInsert)
        self.mainToolBar.addAction(self.actDelete)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actAlignLeft)
        self.mainToolBar.addAction(self.actAlignCenter)
        self.mainToolBar.addAction(self.actAlignRight)
        self.mainToolBar.addAction(self.actFontBold)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actExit)

        self.retranslateUi(MainWindow)
        self.actExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo4_4, 自定义代理组件的应用"))
        self.groupBox.setTitle(_translate("MainWindow", "tableView"))
        self.groupBox_2.setTitle(_translate("MainWindow", "plainTextEdit"))
        self.actOpen.setText(_translate("MainWindow", "打开文件"))
        self.actOpen.setToolTip(_translate("MainWindow", "打开文件"))
        self.actSave.setText(_translate("MainWindow", "另存文件"))
        self.actSave.setToolTip(_translate("MainWindow", "表格内容另存为文件"))
        self.actAppend.setText(_translate("MainWindow", "添加行"))
        self.actAppend.setToolTip(_translate("MainWindow", "添加一行"))
        self.actInsert.setText(_translate("MainWindow", "插入行"))
        self.actInsert.setToolTip(_translate("MainWindow", "插入一行"))
        self.actDelete.setText(_translate("MainWindow", "删除行"))
        self.actDelete.setToolTip(_translate("MainWindow", "删除当前行"))
        self.actExit.setText(_translate("MainWindow", "退出"))
        self.actExit.setToolTip(_translate("MainWindow", "退出"))
        self.actModelData.setText(_translate("MainWindow", "模型数据"))
        self.actModelData.setToolTip(_translate("MainWindow", "模型数据显示到文本框里"))
        self.actAlignLeft.setText(_translate("MainWindow", "居左"))
        self.actAlignLeft.setToolTip(_translate("MainWindow", "文字左对齐"))
        self.actAlignCenter.setText(_translate("MainWindow", "居中"))
        self.actAlignCenter.setToolTip(_translate("MainWindow", "文字居中"))
        self.actAlignRight.setText(_translate("MainWindow", "居右"))
        self.actAlignRight.setToolTip(_translate("MainWindow", "文字右对齐"))
        self.actFontBold.setText(_translate("MainWindow", "粗体"))
        self.actFontBold.setToolTip(_translate("MainWindow", "粗体字体"))


import res_rc
