# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 579)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.frameSetup = QtWidgets.QFrame(self.centralWidget)
        self.frameSetup.setGeometry(QtCore.QRect(10, 15, 271, 491))
        self.frameSetup.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameSetup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSetup.setObjectName("frameSetup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameSetup)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frameSetup)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.comboCamera = QtWidgets.QComboBox(self.groupBox_2)
        self.comboCamera.setObjectName("comboCamera")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.comboCamera.addItem("")
        self.gridLayout.addWidget(self.comboCamera, 0, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.sliderH = QtWidgets.QSlider(self.groupBox_2)
        self.sliderH.setMinimum(-180)
        self.sliderH.setMaximum(180)
        self.sliderH.setOrientation(QtCore.Qt.Horizontal)
        self.sliderH.setObjectName("sliderH")
        self.gridLayout.addWidget(self.sliderH, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.groupBox_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnMoveUp = QtWidgets.QToolButton(self.frame)
        self.btnMoveUp.setText("")
        self.btnMoveUp.setArrowType(QtCore.Qt.UpArrow)
        self.btnMoveUp.setObjectName("btnMoveUp")
        self.gridLayout_4.addWidget(self.btnMoveUp, 0, 1, 1, 1)
        self.btnMoveLeft = QtWidgets.QToolButton(self.frame)
        self.btnMoveLeft.setText("")
        self.btnMoveLeft.setArrowType(QtCore.Qt.LeftArrow)
        self.btnMoveLeft.setObjectName("btnMoveLeft")
        self.gridLayout_4.addWidget(self.btnMoveLeft, 1, 0, 1, 1)
        self.btnMoveRight = QtWidgets.QToolButton(self.frame)
        self.btnMoveRight.setText("")
        self.btnMoveRight.setArrowType(QtCore.Qt.RightArrow)
        self.btnMoveRight.setObjectName("btnMoveRight")
        self.gridLayout_4.addWidget(self.btnMoveRight, 1, 2, 1, 1)
        self.btnMoveDown = QtWidgets.QToolButton(self.frame)
        self.btnMoveDown.setText("")
        self.btnMoveDown.setArrowType(QtCore.Qt.DownArrow)
        self.btnMoveDown.setObjectName("btnMoveDown")
        self.gridLayout_4.addWidget(self.btnMoveDown, 2, 1, 1, 1)
        self.btnResetCamera = QtWidgets.QToolButton(self.frame)
        self.btnResetCamera.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/326.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnResetCamera.setIcon(icon)
        self.btnResetCamera.setObjectName("btnResetCamera")
        self.gridLayout_4.addWidget(self.btnResetCamera, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 2, 3, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.sliderV = QtWidgets.QSlider(self.groupBox_2)
        self.sliderV.setMinimum(-180)
        self.sliderV.setMaximum(180)
        self.sliderV.setOrientation(QtCore.Qt.Horizontal)
        self.sliderV.setObjectName("sliderV")
        self.gridLayout.addWidget(self.sliderV, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.sliderZoom = QtWidgets.QSlider(self.groupBox_2)
        self.sliderZoom.setMinimum(10)
        self.sliderZoom.setMaximum(500)
        self.sliderZoom.setProperty("value", 100)
        self.sliderZoom.setOrientation(QtCore.Qt.Horizontal)
        self.sliderZoom.setObjectName("sliderZoom")
        self.gridLayout.addWidget(self.sliderZoom, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frameSetup)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setIndent(10)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.chkBoxAxisTitle = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkBoxAxisTitle.setChecked(True)
        self.chkBoxAxisTitle.setObjectName("chkBoxAxisTitle")
        self.gridLayout_2.addWidget(self.chkBoxAxisTitle, 7, 0, 1, 1)
        self.chkBoxShadow = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkBoxShadow.setChecked(True)
        self.chkBoxShadow.setObjectName("chkBoxShadow")
        self.gridLayout_2.addWidget(self.chkBoxShadow, 5, 0, 1, 1)
        self.chkBoxBackground = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkBoxBackground.setChecked(True)
        self.chkBoxBackground.setObjectName("chkBoxBackground")
        self.gridLayout_2.addWidget(self.chkBoxBackground, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setIndent(10)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setIndent(10)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.cBoxTheme = QtWidgets.QComboBox(self.groupBox_3)
        self.cBoxTheme.setObjectName("cBoxTheme")
        self.cBoxTheme.addItem("")
        self.cBoxTheme.addItem("")
        self.cBoxTheme.addItem("")
        self.cBoxTheme.addItem("")
        self.cBoxTheme.addItem("")
        self.cBoxTheme.addItem("")
        self.cBoxTheme.addItem("")
        self.cBoxTheme.addItem("")
        self.gridLayout_2.addWidget(self.cBoxTheme, 0, 1, 1, 1)
        self.spinFontSize = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinFontSize.setMinimum(5)
        self.spinFontSize.setProperty("value", 10)
        self.spinFontSize.setObjectName("spinFontSize")
        self.gridLayout_2.addWidget(self.spinFontSize, 1, 1, 1, 1)
        self.chkBoxGrid = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkBoxGrid.setChecked(True)
        self.chkBoxGrid.setObjectName("chkBoxGrid")
        self.gridLayout_2.addWidget(self.chkBoxGrid, 3, 1, 1, 1)
        self.chkBoxAxisBackground = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkBoxAxisBackground.setObjectName("chkBoxAxisBackground")
        self.gridLayout_2.addWidget(self.chkBoxAxisBackground, 7, 1, 1, 1)
        self.chkBoxReverse = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkBoxReverse.setObjectName("chkBoxReverse")
        self.gridLayout_2.addWidget(self.chkBoxReverse, 5, 1, 1, 1)
        self.cBoxSelectionMode = QtWidgets.QComboBox(self.groupBox_3)
        self.cBoxSelectionMode.setObjectName("cBoxSelectionMode")
        self.cBoxSelectionMode.addItem("")
        self.cBoxSelectionMode.addItem("")
        self.cBoxSelectionMode.addItem("")
        self.cBoxSelectionMode.addItem("")
        self.cBoxSelectionMode.addItem("")
        self.cBoxSelectionMode.addItem("")
        self.cBoxSelectionMode.addItem("")
        self.cBoxSelectionMode.addItem("")
        self.cBoxSelectionMode.addItem("")
        self.cBoxSelectionMode.addItem("")
        self.gridLayout_2.addWidget(self.cBoxSelectionMode, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frameSetup)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setIndent(10)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.cBoxBarStyle = QtWidgets.QComboBox(self.groupBox_4)
        self.cBoxBarStyle.setObjectName("cBoxBarStyle")
        self.cBoxBarStyle.addItem("")
        self.cBoxBarStyle.addItem("")
        self.cBoxBarStyle.addItem("")
        self.cBoxBarStyle.addItem("")
        self.cBoxBarStyle.addItem("")
        self.cBoxBarStyle.addItem("")
        self.cBoxBarStyle.addItem("")
        self.cBoxBarStyle.addItem("")
        self.cBoxBarStyle.addItem("")
        self.cBoxBarStyle.addItem("")
        self.cBoxBarStyle.addItem("")
        self.gridLayout_3.addWidget(self.cBoxBarStyle, 0, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setIndent(10)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.spinItemSize = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spinItemSize.setMaximum(1.0)
        self.spinItemSize.setSingleStep(0.01)
        self.spinItemSize.setProperty("value", 0.15)
        self.spinItemSize.setObjectName("spinItemSize")
        self.gridLayout_3.addWidget(self.spinItemSize, 1, 1, 1, 1)
        self.chkBoxSmooth = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkBoxSmooth.setChecked(True)
        self.chkBoxSmooth.setObjectName("chkBoxSmooth")
        self.gridLayout_3.addWidget(self.chkBoxSmooth, 1, 2, 1, 1)
        self.chkBoxItemLabel = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkBoxItemLabel.setChecked(True)
        self.chkBoxItemLabel.setObjectName("chkBoxItemLabel")
        self.gridLayout_3.addWidget(self.chkBoxItemLabel, 2, 1, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actSeries_BaseColor = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/720.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSeries_BaseColor.setIcon(icon1)
        self.actSeries_BaseColor.setObjectName("actSeries_BaseColor")
        self.actPoint_ChangeValue = QtWidgets.QAction(MainWindow)
        self.actPoint_ChangeValue.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/810.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actPoint_ChangeValue.setIcon(icon2)
        self.actPoint_ChangeValue.setObjectName("actPoint_ChangeValue")
        self.actData_Delete = QtWidgets.QAction(MainWindow)
        self.actData_Delete.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/318.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actData_Delete.setIcon(icon3)
        self.actData_Delete.setObjectName("actData_Delete")
        self.actData_Add = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/316.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actData_Add.setIcon(icon4)
        self.actData_Add.setObjectName("actData_Add")
        self.actClose = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actClose.setIcon(icon5)
        self.actClose.setObjectName("actClose")
        self.toolBar.addAction(self.actSeries_BaseColor)
        self.toolBar.addAction(self.actPoint_ChangeValue)
        self.toolBar.addAction(self.actData_Add)
        self.toolBar.addAction(self.actData_Delete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actClose)
        self.label_6.setBuddy(self.comboCamera)
        self.label_7.setBuddy(self.sliderH)
        self.label_8.setBuddy(self.sliderV)
        self.label_9.setBuddy(self.sliderZoom)
        self.label.setBuddy(self.cBoxTheme)
        self.label_4.setBuddy(self.spinFontSize)
        self.label_2.setBuddy(self.cBoxBarStyle)
        self.label_5.setBuddy(self.spinItemSize)

        self.retranslateUi(MainWindow)
        self.comboCamera.setCurrentIndex(2)
        self.cBoxSelectionMode.setCurrentIndex(1)
        self.cBoxBarStyle.setCurrentIndex(7)
        self.actClose.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Q3DScatter绘图"))
        self.groupBox_2.setTitle(_translate("MainWindow", "旋转和平移"))
        self.label_6.setText(_translate("MainWindow", "预设视角"))
        self.comboCamera.setItemText(0, _translate("MainWindow", "FrontLow"))
        self.comboCamera.setItemText(1, _translate("MainWindow", "Front"))
        self.comboCamera.setItemText(2, _translate("MainWindow", "FrontHigh"))
        self.comboCamera.setItemText(3, _translate("MainWindow", "LeftLow"))
        self.comboCamera.setItemText(4, _translate("MainWindow", "Left"))
        self.comboCamera.setItemText(5, _translate("MainWindow", "LeftHigh"))
        self.comboCamera.setItemText(6, _translate("MainWindow", "RightLow"))
        self.comboCamera.setItemText(7, _translate("MainWindow", "Right"))
        self.comboCamera.setItemText(8, _translate("MainWindow", "RightHigh"))
        self.comboCamera.setItemText(9, _translate("MainWindow", "BehindLow"))
        self.comboCamera.setItemText(10, _translate("MainWindow", "Behind"))
        self.comboCamera.setItemText(11, _translate("MainWindow", "BehindHigh"))
        self.comboCamera.setItemText(12, _translate("MainWindow", "IsometricLeft"))
        self.comboCamera.setItemText(13, _translate("MainWindow", "IsometricLeftHigh"))
        self.comboCamera.setItemText(14, _translate("MainWindow", "IsometricRight"))
        self.comboCamera.setItemText(15, _translate("MainWindow", "IsometricRightHigh"))
        self.comboCamera.setItemText(16, _translate("MainWindow", "DirectlyAbove"))
        self.comboCamera.setItemText(17, _translate("MainWindow", "DirectlyAboveCW45"))
        self.comboCamera.setItemText(18, _translate("MainWindow", "DirectlyAboveCCW45"))
        self.comboCamera.setItemText(19, _translate("MainWindow", "FrontBelow"))
        self.comboCamera.setItemText(20, _translate("MainWindow", "LeftBelow"))
        self.comboCamera.setItemText(21, _translate("MainWindow", "RightBelow"))
        self.comboCamera.setItemText(22, _translate("MainWindow", "BehindBelow"))
        self.comboCamera.setItemText(23, _translate("MainWindow", "DirectlyBelow"))
        self.label_7.setText(_translate("MainWindow", "水平旋转"))
        self.btnResetCamera.setToolTip(_translate("MainWindow", "复位到FrontHigh视角"))
        self.label_8.setText(_translate("MainWindow", "垂直旋转"))
        self.label_9.setText(_translate("MainWindow", "缩  放"))
        self.groupBox_3.setTitle(_translate("MainWindow", "图表总体"))
        self.label.setText(_translate("MainWindow", "图表主题"))
        self.chkBoxAxisTitle.setText(_translate("MainWindow", "显示轴标题"))
        self.chkBoxShadow.setText(_translate("MainWindow", "显示阴影"))
        self.chkBoxBackground.setText(_translate("MainWindow", "显示背景"))
        self.label_4.setText(_translate("MainWindow", "字体大小"))
        self.label_3.setText(_translate("MainWindow", "选择模式"))
        self.cBoxTheme.setItemText(0, _translate("MainWindow", "Qt"))
        self.cBoxTheme.setItemText(1, _translate("MainWindow", "Primary Colors"))
        self.cBoxTheme.setItemText(2, _translate("MainWindow", "Digia"))
        self.cBoxTheme.setItemText(3, _translate("MainWindow", "StoneMoss"))
        self.cBoxTheme.setItemText(4, _translate("MainWindow", "ArmyBlue"))
        self.cBoxTheme.setItemText(5, _translate("MainWindow", "Retro"))
        self.cBoxTheme.setItemText(6, _translate("MainWindow", "Ebony"))
        self.cBoxTheme.setItemText(7, _translate("MainWindow", "Isabelle"))
        self.chkBoxGrid.setText(_translate("MainWindow", "显示背景网格"))
        self.chkBoxAxisBackground.setText(_translate("MainWindow", "显示轴标签背景"))
        self.chkBoxReverse.setText(_translate("MainWindow", "垂直坐标轴反向"))
        self.cBoxSelectionMode.setItemText(0, _translate("MainWindow", "None"))
        self.cBoxSelectionMode.setItemText(1, _translate("MainWindow", "Item"))
        self.cBoxSelectionMode.setItemText(2, _translate("MainWindow", "Row"))
        self.cBoxSelectionMode.setItemText(3, _translate("MainWindow", "Item And Row"))
        self.cBoxSelectionMode.setItemText(4, _translate("MainWindow", "Column"))
        self.cBoxSelectionMode.setItemText(5, _translate("MainWindow", "Item And Column"))
        self.cBoxSelectionMode.setItemText(6, _translate("MainWindow", "Row And Column"))
        self.cBoxSelectionMode.setItemText(7, _translate("MainWindow", "Item Row And Column"))
        self.cBoxSelectionMode.setItemText(8, _translate("MainWindow", "Row Slice"))
        self.cBoxSelectionMode.setItemText(9, _translate("MainWindow", "Column Slice"))
        self.groupBox_4.setTitle(_translate("MainWindow", "序列设置"))
        self.label_2.setText(_translate("MainWindow", "散点形状"))
        self.cBoxBarStyle.setItemText(0, _translate("MainWindow", "Bar"))
        self.cBoxBarStyle.setItemText(1, _translate("MainWindow", "Cube"))
        self.cBoxBarStyle.setItemText(2, _translate("MainWindow", "Pyramid"))
        self.cBoxBarStyle.setItemText(3, _translate("MainWindow", "Cone"))
        self.cBoxBarStyle.setItemText(4, _translate("MainWindow", "Cylinder"))
        self.cBoxBarStyle.setItemText(5, _translate("MainWindow", "BevelBar"))
        self.cBoxBarStyle.setItemText(6, _translate("MainWindow", "BevelCube"))
        self.cBoxBarStyle.setItemText(7, _translate("MainWindow", "Sphere"))
        self.cBoxBarStyle.setItemText(8, _translate("MainWindow", "Minimal"))
        self.cBoxBarStyle.setItemText(9, _translate("MainWindow", "Arrow"))
        self.cBoxBarStyle.setItemText(10, _translate("MainWindow", "Point"))
        self.label_5.setText(_translate("MainWindow", "散点大小"))
        self.chkBoxSmooth.setText(_translate("MainWindow", "光滑效果"))
        self.chkBoxItemLabel.setText(_translate("MainWindow", "选中散点标签可见"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actSeries_BaseColor.setText(_translate("MainWindow", "序列基本颜色"))
        self.actSeries_BaseColor.setToolTip(_translate("MainWindow", "设置序列基本颜色"))
        self.actPoint_ChangeValue.setText(_translate("MainWindow", "修改散点坐标"))
        self.actPoint_ChangeValue.setToolTip(_translate("MainWindow", "修改散点坐标(F2)"))
        self.actPoint_ChangeValue.setShortcut(_translate("MainWindow", "F2"))
        self.actData_Delete.setText(_translate("MainWindow", "删除当前点"))
        self.actData_Delete.setToolTip(_translate("MainWindow", "删除当前点(Del)"))
        self.actData_Delete.setShortcut(_translate("MainWindow", "Del"))
        self.actData_Add.setText(_translate("MainWindow", "添加随机点"))
        self.actData_Add.setToolTip(_translate("MainWindow", "添加随机点(F3)"))
        self.actData_Add.setShortcut(_translate("MainWindow", "F3"))
        self.actClose.setText(_translate("MainWindow", "退出"))
        self.actClose.setToolTip(_translate("MainWindow", "退出"))


import res_rc
