# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 484)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QSpinBox, QDoubleSpinBox{\n"
"    max-width:100px;\n"
"    min-height:20px;\n"
"}")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frameSetup = QtWidgets.QFrame(self.splitter)
        self.frameSetup.setEnabled(True)
        self.frameSetup.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frameSetup.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameSetup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSetup.setObjectName("frameSetup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameSetup)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frameSetup)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(11, 5, 11, 5)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setIndent(10)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboTheme = QtWidgets.QComboBox(self.groupBox)
        self.comboTheme.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboTheme.setObjectName("comboTheme")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.horizontalLayout.addWidget(self.comboTheme)
        self.chkBox_Legend = QtWidgets.QCheckBox(self.groupBox)
        self.chkBox_Legend.setChecked(True)
        self.chkBox_Legend.setObjectName("chkBox_Legend")
        self.horizontalLayout.addWidget(self.chkBox_Legend)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frameSetup)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(11, 5, 11, 5)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setIndent(10)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinMag_Min = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinMag_Min.setMaximumSize(QtCore.QSize(102, 16777215))
        self.spinMag_Min.setDecimals(1)
        self.spinMag_Min.setMinimum(-90000.0)
        self.spinMag_Min.setMaximum(90000.0)
        self.spinMag_Min.setSingleStep(10.0)
        self.spinMag_Min.setProperty("value", -40.0)
        self.spinMag_Min.setObjectName("spinMag_Min")
        self.gridLayout_3.addWidget(self.spinMag_Min, 0, 1, 1, 1)
        self.btnMag_SetRange = QtWidgets.QPushButton(self.groupBox_3)
        self.btnMag_SetRange.setObjectName("btnMag_SetRange")
        self.gridLayout_3.addWidget(self.btnMag_SetRange, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setIndent(10)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.spinMag_Max = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinMag_Max.setDecimals(1)
        self.spinMag_Max.setMinimum(-90000.0)
        self.spinMag_Max.setMaximum(90000.0)
        self.spinMag_Max.setSingleStep(10.0)
        self.spinMag_Max.setProperty("value", 10.0)
        self.spinMag_Max.setObjectName("spinMag_Max")
        self.gridLayout_3.addWidget(self.spinMag_Max, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setIndent(10)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinMag_Ticks = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinMag_Ticks.setMinimum(3)
        self.spinMag_Ticks.setMaximum(1000)
        self.spinMag_Ticks.setProperty("value", 6)
        self.spinMag_Ticks.setDisplayIntegerBase(10)
        self.spinMag_Ticks.setObjectName("spinMag_Ticks")
        self.gridLayout_3.addWidget(self.spinMag_Ticks, 2, 1, 1, 1)
        self.chkBoxMag_Point = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkBoxMag_Point.setChecked(True)
        self.chkBoxMag_Point.setObjectName("chkBoxMag_Point")
        self.gridLayout_3.addWidget(self.chkBoxMag_Point, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frameSetup)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setContentsMargins(11, 5, 11, 5)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setVerticalSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setIndent(10)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.spinPh_Min = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spinPh_Min.setDecimals(1)
        self.spinPh_Min.setMinimum(-50000.0)
        self.spinPh_Min.setMaximum(50000.0)
        self.spinPh_Min.setSingleStep(10.0)
        self.spinPh_Min.setProperty("value", -200.0)
        self.spinPh_Min.setObjectName("spinPh_Min")
        self.gridLayout_4.addWidget(self.spinPh_Min, 0, 1, 1, 1)
        self.btnPh_SetRange = QtWidgets.QPushButton(self.groupBox_5)
        self.btnPh_SetRange.setObjectName("btnPh_SetRange")
        self.gridLayout_4.addWidget(self.btnPh_SetRange, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setIndent(10)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.spinPh_Max = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spinPh_Max.setDecimals(1)
        self.spinPh_Max.setMinimum(-50000.0)
        self.spinPh_Max.setMaximum(50000.0)
        self.spinPh_Max.setSingleStep(10.0)
        self.spinPh_Max.setProperty("value", 0.0)
        self.spinPh_Max.setObjectName("spinPh_Max")
        self.gridLayout_4.addWidget(self.spinPh_Max, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setIndent(10)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 2, 0, 1, 1)
        self.spinPh_Ticks = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinPh_Ticks.setMinimum(3)
        self.spinPh_Ticks.setMaximum(1000)
        self.spinPh_Ticks.setProperty("value", 6)
        self.spinPh_Ticks.setDisplayIntegerBase(10)
        self.spinPh_Ticks.setObjectName("spinPh_Ticks")
        self.gridLayout_4.addWidget(self.spinPh_Ticks, 2, 1, 1, 1)
        self.chkBoxPh_Point = QtWidgets.QCheckBox(self.groupBox_5)
        self.chkBoxPh_Point.setChecked(True)
        self.chkBoxPh_Point.setObjectName("chkBoxPh_Point")
        self.gridLayout_4.addWidget(self.chkBoxPh_Point, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frameSetup)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setContentsMargins(11, 5, 11, 5)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.spinX_Max = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spinX_Max.setMinimum(0.0)
        self.spinX_Max.setMaximum(9000000.0)
        self.spinX_Max.setSingleStep(10.0)
        self.spinX_Max.setProperty("value", 100.0)
        self.spinX_Max.setObjectName("spinX_Max")
        self.gridLayout.addWidget(self.spinX_Max, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setIndent(10)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.spinX_MinorTicks = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinX_MinorTicks.setMinimum(1)
        self.spinX_MinorTicks.setMaximum(100)
        self.spinX_MinorTicks.setProperty("value", 9)
        self.spinX_MinorTicks.setObjectName("spinX_MinorTicks")
        self.gridLayout.addWidget(self.spinX_MinorTicks, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setIndent(10)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.spinX_Min = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spinX_Min.setDecimals(3)
        self.spinX_Min.setMinimum(0.001)
        self.spinX_Min.setMaximum(50000.0)
        self.spinX_Min.setSingleStep(0.1)
        self.spinX_Min.setProperty("value", 0.1)
        self.spinX_Min.setObjectName("spinX_Min")
        self.gridLayout.addWidget(self.spinX_Min, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setIndent(10)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.btnX_SetRange = QtWidgets.QPushButton(self.groupBox_4)
        self.btnX_SetRange.setObjectName("btnX_SetRange")
        self.gridLayout.addWidget(self.btnX_SetRange, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frameChart = QtWidgets.QFrame(self.splitter)
        self.frameChart.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameChart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameChart.setObjectName("frameChart")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameChart)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chartView = QmyChartView(self.frameChart)
        self.chartView.setObjectName("chartView")
        self.verticalLayout.addWidget(self.chartView)
        self.verticalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actZoomReset = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/414.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomReset.setIcon(icon)
        self.actZoomReset.setObjectName("actZoomReset")
        self.actQuit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actQuit.setIcon(icon1)
        self.actQuit.setObjectName("actQuit")
        self.actZoomIn = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/418.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomIn.setIcon(icon2)
        self.actZoomIn.setObjectName("actZoomIn")
        self.actZoomOut = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/416.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomOut.setIcon(icon3)
        self.actZoomOut.setObjectName("actZoomOut")
        self.actOpen = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/001.GIF"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actOpen.setIcon(icon4)
        self.actOpen.setObjectName("actOpen")
        self.mainToolBar.addAction(self.actOpen)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actZoomIn)
        self.mainToolBar.addAction(self.actZoomOut)
        self.mainToolBar.addAction(self.actZoomReset)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actQuit)

        self.retranslateUi(MainWindow)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "对数坐标轴与多坐标轴"))
        self.groupBox.setTitle(_translate("MainWindow", "图表"))
        self.label_2.setText(_translate("MainWindow", "主题"))
        self.comboTheme.setToolTip(_translate("MainWindow", "设置图表主题"))
        self.comboTheme.setItemText(0, _translate("MainWindow", "Light"))
        self.comboTheme.setItemText(1, _translate("MainWindow", "BlueCerulean"))
        self.comboTheme.setItemText(2, _translate("MainWindow", "Dark"))
        self.comboTheme.setItemText(3, _translate("MainWindow", "BrownSand"))
        self.comboTheme.setItemText(4, _translate("MainWindow", "BlueNcs"))
        self.comboTheme.setItemText(5, _translate("MainWindow", "HighContrast"))
        self.comboTheme.setItemText(6, _translate("MainWindow", "BlueIcy"))
        self.comboTheme.setItemText(7, _translate("MainWindow", "Qt"))
        self.chkBox_Legend.setText(_translate("MainWindow", "显示图例"))
        self.groupBox_3.setTitle(_translate("MainWindow", "幅频曲线"))
        self.label_5.setText(_translate("MainWindow", "最小值"))
        self.spinMag_Min.setSuffix(_translate("MainWindow", " dB"))
        self.btnMag_SetRange.setText(_translate("MainWindow", "设置范围"))
        self.label_6.setText(_translate("MainWindow", "最大值"))
        self.spinMag_Max.setSuffix(_translate("MainWindow", " dB"))
        self.label_3.setText(_translate("MainWindow", "主分度个数"))
        self.chkBoxMag_Point.setText(_translate("MainWindow", "显示数据点"))
        self.groupBox_5.setTitle(_translate("MainWindow", "相频曲线"))
        self.label_9.setText(_translate("MainWindow", "最小值"))
        self.spinPh_Min.setSuffix(_translate("MainWindow", "°"))
        self.btnPh_SetRange.setText(_translate("MainWindow", "设置范围"))
        self.label_10.setText(_translate("MainWindow", "最大值"))
        self.spinPh_Max.setSuffix(_translate("MainWindow", "°"))
        self.label_11.setText(_translate("MainWindow", "主分度个数"))
        self.chkBoxPh_Point.setText(_translate("MainWindow", "显示数据点"))
        self.groupBox_4.setTitle(_translate("MainWindow", "频率坐标轴--QLogValueAxis"))
        self.label.setText(_translate("MainWindow", "次分度个数"))
        self.label_8.setText(_translate("MainWindow", "最大值"))
        self.label_7.setText(_translate("MainWindow", "最小值"))
        self.btnX_SetRange.setText(_translate("MainWindow", "设置范围"))
        self.label_4.setText(_translate("MainWindow", "(刷新时才生效)"))
        self.actZoomReset.setText(_translate("MainWindow", "原始大小"))
        self.actZoomReset.setToolTip(_translate("MainWindow", "原始大小"))
        self.actQuit.setText(_translate("MainWindow", "退出"))
        self.actQuit.setToolTip(_translate("MainWindow", "退出"))
        self.actZoomIn.setText(_translate("MainWindow", "放大"))
        self.actZoomIn.setToolTip(_translate("MainWindow", "放大"))
        self.actZoomOut.setText(_translate("MainWindow", "缩小"))
        self.actZoomOut.setToolTip(_translate("MainWindow", "缩小"))
        self.actOpen.setText(_translate("MainWindow", "打开文件"))
        self.actOpen.setToolTip(_translate("MainWindow", "打开数据文件"))

from myChartView import QmyChartView
import res_rc
