# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 454)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralWidget)
        self.mdiArea.setGeometry(QtCore.QRect(45, 30, 581, 341))
        self.mdiArea.setObjectName("mdiArea")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setAutoFillBackground(True)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actDoc_New = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/100.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actDoc_New.setIcon(icon)
        self.actDoc_New.setObjectName("actDoc_New")
        self.actQuit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actQuit.setIcon(icon1)
        self.actQuit.setObjectName("actQuit")
        self.actDoc_Open = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/122.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actDoc_Open.setIcon(icon2)
        self.actDoc_Open.setObjectName("actDoc_Open")
        self.actEdit_Font = QtWidgets.QAction(MainWindow)
        self.actEdit_Font.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/506.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEdit_Font.setIcon(icon3)
        self.actEdit_Font.setObjectName("actEdit_Font")
        self.actEdit_Cut = QtWidgets.QAction(MainWindow)
        self.actEdit_Cut.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/200.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEdit_Cut.setIcon(icon4)
        self.actEdit_Cut.setObjectName("actEdit_Cut")
        self.actEdit_Copy = QtWidgets.QAction(MainWindow)
        self.actEdit_Copy.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/202.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEdit_Copy.setIcon(icon5)
        self.actEdit_Copy.setObjectName("actEdit_Copy")
        self.actEdit_Paste = QtWidgets.QAction(MainWindow)
        self.actEdit_Paste.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/204.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEdit_Paste.setIcon(icon6)
        self.actEdit_Paste.setObjectName("actEdit_Paste")
        self.actMDI_Mode = QtWidgets.QAction(MainWindow)
        self.actMDI_Mode.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/230.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actMDI_Mode.setIcon(icon7)
        self.actMDI_Mode.setObjectName("actMDI_Mode")
        self.actMDI_Cascade = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/400.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actMDI_Cascade.setIcon(icon8)
        self.actMDI_Cascade.setObjectName("actMDI_Cascade")
        self.actMDI_Tile = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/406.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actMDI_Tile.setIcon(icon9)
        self.actMDI_Tile.setObjectName("actMDI_Tile")
        self.actDoc_CloseALL = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/images/128.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actDoc_CloseALL.setIcon(icon10)
        self.actDoc_CloseALL.setObjectName("actDoc_CloseALL")
        self.mainToolBar.addAction(self.actDoc_New)
        self.mainToolBar.addAction(self.actDoc_Open)
        self.mainToolBar.addAction(self.actDoc_CloseALL)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actEdit_Cut)
        self.mainToolBar.addAction(self.actEdit_Copy)
        self.mainToolBar.addAction(self.actEdit_Paste)
        self.mainToolBar.addAction(self.actEdit_Font)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actMDI_Mode)
        self.mainToolBar.addAction(self.actMDI_Cascade)
        self.mainToolBar.addAction(self.actMDI_Tile)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actQuit)

        self.retranslateUi(MainWindow)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo6_4, MDI应用程序"))
        self.actDoc_New.setText(_translate("MainWindow", "新建文档"))
        self.actDoc_New.setToolTip(_translate("MainWindow", "新建文档窗口"))
        self.actQuit.setText(_translate("MainWindow", "退出"))
        self.actQuit.setToolTip(_translate("MainWindow", "退出本系统"))
        self.actDoc_Open.setText(_translate("MainWindow", "打开文档"))
        self.actDoc_Open.setToolTip(_translate("MainWindow", "打开文档"))
        self.actEdit_Font.setText(_translate("MainWindow", "字体设置"))
        self.actEdit_Font.setToolTip(_translate("MainWindow", "字体设置"))
        self.actEdit_Cut.setText(_translate("MainWindow", "剪切"))
        self.actEdit_Cut.setToolTip(_translate("MainWindow", "剪切"))
        self.actEdit_Copy.setText(_translate("MainWindow", "复制"))
        self.actEdit_Copy.setToolTip(_translate("MainWindow", "复制"))
        self.actEdit_Paste.setText(_translate("MainWindow", "粘贴"))
        self.actEdit_Paste.setToolTip(_translate("MainWindow", "粘贴"))
        self.actMDI_Mode.setText(_translate("MainWindow", "MDI模式"))
        self.actMDI_Mode.setToolTip(_translate("MainWindow", "窗口模式或页面模式"))
        self.actMDI_Cascade.setText(_translate("MainWindow", "级联展开"))
        self.actMDI_Cascade.setToolTip(_translate("MainWindow", "窗口级联展开"))
        self.actMDI_Tile.setText(_translate("MainWindow", "平铺展开"))
        self.actMDI_Tile.setToolTip(_translate("MainWindow", "窗口平铺展开"))
        self.actDoc_CloseALL.setText(_translate("MainWindow", "关闭全部"))
        self.actDoc_CloseALL.setToolTip(_translate("MainWindow", "关闭所有窗口"))

import res_rc
