# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(305, 198)
        font = QtGui.QFont()
        font.setPointSize(9)
        Widget.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAlign_Left = QtWidgets.QPushButton(Widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/508.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlign_Left.setIcon(icon)
        self.btnAlign_Left.setCheckable(True)
        self.btnAlign_Left.setChecked(True)
        self.btnAlign_Left.setAutoExclusive(True)
        self.btnAlign_Left.setFlat(True)
        self.btnAlign_Left.setObjectName("btnAlign_Left")
        self.horizontalLayout.addWidget(self.btnAlign_Left)
        self.btnAlign_Center = QtWidgets.QPushButton(Widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/510.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlign_Center.setIcon(icon1)
        self.btnAlign_Center.setCheckable(True)
        self.btnAlign_Center.setChecked(False)
        self.btnAlign_Center.setAutoExclusive(True)
        self.btnAlign_Center.setFlat(True)
        self.btnAlign_Center.setObjectName("btnAlign_Center")
        self.horizontalLayout.addWidget(self.btnAlign_Center)
        self.btnAlign_Right = QtWidgets.QPushButton(Widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/512.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlign_Right.setIcon(icon2)
        self.btnAlign_Right.setCheckable(True)
        self.btnAlign_Right.setChecked(False)
        self.btnAlign_Right.setAutoExclusive(True)
        self.btnAlign_Right.setFlat(True)
        self.btnAlign_Right.setObjectName("btnAlign_Right")
        self.horizontalLayout.addWidget(self.btnAlign_Right)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnFont_Bold = QtWidgets.QPushButton(Widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/500.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFont_Bold.setIcon(icon3)
        self.btnFont_Bold.setCheckable(True)
        self.btnFont_Bold.setObjectName("btnFont_Bold")
        self.horizontalLayout_2.addWidget(self.btnFont_Bold)
        self.btnFont_Italic = QtWidgets.QPushButton(Widget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/502.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFont_Italic.setIcon(icon4)
        self.btnFont_Italic.setCheckable(True)
        self.btnFont_Italic.setObjectName("btnFont_Italic")
        self.horizontalLayout_2.addWidget(self.btnFont_Italic)
        self.btnFont_UnderLine = QtWidgets.QPushButton(Widget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/504.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFont_UnderLine.setIcon(icon5)
        self.btnFont_UnderLine.setCheckable(True)
        self.btnFont_UnderLine.setObjectName("btnFont_UnderLine")
        self.horizontalLayout_2.addWidget(self.btnFont_UnderLine)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(Widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chkBox_Readonly = QtWidgets.QCheckBox(Widget)
        self.chkBox_Readonly.setObjectName("chkBox_Readonly")
        self.horizontalLayout_3.addWidget(self.chkBox_Readonly)
        self.chkbox_Enable = QtWidgets.QCheckBox(Widget)
        self.chkbox_Enable.setChecked(True)
        self.chkbox_Enable.setObjectName("chkbox_Enable")
        self.horizontalLayout_3.addWidget(self.chkbox_Enable)
        self.chkBox_ClearButton = QtWidgets.QCheckBox(Widget)
        self.chkBox_ClearButton.setObjectName("chkBox_ClearButton")
        self.horizontalLayout_3.addWidget(self.chkBox_ClearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.editInput = QtWidgets.QLineEdit(Widget)
        self.editInput.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.editInput.setFont(font)
        self.editInput.setObjectName("editInput")
        self.verticalLayout.addWidget(self.editInput)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Demo3_2，按钮的使用"))
        self.btnAlign_Left.setText(_translate("Widget", "居左"))
        self.btnAlign_Center.setText(_translate("Widget", "居中"))
        self.btnAlign_Right.setText(_translate("Widget", "居右"))
        self.btnFont_Bold.setText(_translate("Widget", "粗体"))
        self.btnFont_Italic.setText(_translate("Widget", "斜体"))
        self.btnFont_UnderLine.setText(_translate("Widget", "下划线"))
        self.chkBox_Readonly.setText(_translate("Widget", "Readonly"))
        self.chkbox_Enable.setText(_translate("Widget", "Enabled"))
        self.chkBox_ClearButton.setText(_translate("Widget", "ClearButtonEnabled"))
        self.editInput.setText(_translate("Widget", "测试显示文本"))

import res_rc
