# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 506)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Data = QtWidgets.QWidget()
        self.tab_Data.setObjectName("tab_Data")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_Data)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.tab_Data)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(self.frame)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(50)
        self.tableView.verticalHeader().setDefaultSectionSize(24)
        self.verticalLayout.addWidget(self.tableView)
        self.verticalLayout_3.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_Data, "")
        self.tab_Setup = QtWidgets.QWidget()
        self.tab_Setup.setEnabled(False)
        self.tab_Setup.setObjectName("tab_Setup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_Setup)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameData = QtWidgets.QFrame(self.tab_Setup)
        self.frameData.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameData.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameData.setObjectName("frameData")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameData)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.frameData)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboTheme = QtWidgets.QComboBox(self.groupBox)
        self.comboTheme.setMinimumSize(QtCore.QSize(120, 0))
        self.comboTheme.setObjectName("comboTheme")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.comboTheme.addItem("")
        self.gridLayout_2.addWidget(self.comboTheme, 0, 1, 1, 1)
        self.chkBox_Legend = QtWidgets.QCheckBox(self.groupBox)
        self.chkBox_Legend.setChecked(True)
        self.chkBox_Legend.setObjectName("chkBox_Legend")
        self.gridLayout_2.addWidget(self.chkBox_Legend, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frameData)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.chkBox_Caps = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkBox_Caps.setObjectName("chkBox_Caps")
        self.verticalLayout_7.addWidget(self.chkBox_Caps)
        self.chkBox_Outline = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkBox_Outline.setObjectName("chkBox_Outline")
        self.verticalLayout_7.addWidget(self.chkBox_Outline)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frameData)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinY_Min = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinY_Min.setMaximum(1000000.0)
        self.spinY_Min.setObjectName("spinY_Min")
        self.gridLayout_3.addWidget(self.spinY_Min, 0, 1, 1, 1)
        self.btnY_SetRange = QtWidgets.QPushButton(self.groupBox_3)
        self.btnY_SetRange.setObjectName("btnY_SetRange")
        self.gridLayout_3.addWidget(self.btnY_SetRange, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.spinY_Max = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinY_Max.setMaximum(1000000.0)
        self.spinY_Max.setProperty("value", 20.0)
        self.spinY_Max.setObjectName("spinY_Max")
        self.gridLayout_3.addWidget(self.spinY_Max, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinY_Ticks = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinY_Ticks.setMinimum(3)
        self.spinY_Ticks.setMaximum(1000)
        self.spinY_Ticks.setProperty("value", 5)
        self.spinY_Ticks.setDisplayIntegerBase(10)
        self.spinY_Ticks.setObjectName("spinY_Ticks")
        self.gridLayout_3.addWidget(self.spinY_Ticks, 2, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frameData)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboDateFormat = QtWidgets.QComboBox(self.groupBox_4)
        self.comboDateFormat.setEditable(True)
        self.comboDateFormat.setObjectName("comboDateFormat")
        self.comboDateFormat.addItem("")
        self.comboDateFormat.addItem("")
        self.comboDateFormat.addItem("")
        self.comboDateFormat.addItem("")
        self.gridLayout.addWidget(self.comboDateFormat, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.btnX_Ticks = QtWidgets.QSpinBox(self.groupBox_4)
        self.btnX_Ticks.setMinimum(3)
        self.btnX_Ticks.setMaximum(1000)
        self.btnX_Ticks.setProperty("value", 10)
        self.btnX_Ticks.setDisplayIntegerBase(10)
        self.btnX_Ticks.setObjectName("btnX_Ticks")
        self.gridLayout.addWidget(self.btnX_Ticks, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frameData)
        self.tabWidget.addTab(self.tab_Setup, "")
        self.frame_chart = QtWidgets.QFrame(self.splitter)
        self.frame_chart.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_chart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_chart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_chart.setObjectName("frame_chart")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_chart)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chartView = QmyChartView(self.frame_chart)
        self.chartView.setObjectName("chartView")
        self.verticalLayout_4.addWidget(self.chartView)
        self.verticalLayout_6.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 593, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actZoomReset = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/414.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomReset.setIcon(icon)
        self.actZoomReset.setObjectName("actZoomReset")
        self.actQuit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actQuit.setIcon(icon1)
        self.actQuit.setObjectName("actQuit")
        self.actZoomIn = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/418.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomIn.setIcon(icon2)
        self.actZoomIn.setObjectName("actZoomIn")
        self.actZoomOut = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/416.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomOut.setIcon(icon3)
        self.actZoomOut.setObjectName("actZoomOut")
        self.actOpen = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/001.GIF"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actOpen.setIcon(icon4)
        self.actOpen.setObjectName("actOpen")
        self.mainToolBar.addAction(self.actOpen)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actZoomIn)
        self.mainToolBar.addAction(self.actZoomOut)
        self.mainToolBar.addAction(self.actZoomReset)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actQuit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.actQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "蜡烛图，时间日期坐标轴"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Data), _translate("MainWindow", "数据"))
        self.groupBox.setTitle(_translate("MainWindow", "图表"))
        self.label.setText(_translate("MainWindow", "图表主题"))
        self.comboTheme.setItemText(0, _translate("MainWindow", "Light"))
        self.comboTheme.setItemText(1, _translate("MainWindow", "BlueCerulean"))
        self.comboTheme.setItemText(2, _translate("MainWindow", "Dark"))
        self.comboTheme.setItemText(3, _translate("MainWindow", "BrownSand"))
        self.comboTheme.setItemText(4, _translate("MainWindow", "BlueNcs"))
        self.comboTheme.setItemText(5, _translate("MainWindow", "HighContrast"))
        self.comboTheme.setItemText(6, _translate("MainWindow", "BlueIcy"))
        self.comboTheme.setItemText(7, _translate("MainWindow", "Qt"))
        self.chkBox_Legend.setText(_translate("MainWindow", "显示图例"))
        self.groupBox_2.setTitle(_translate("MainWindow", "蜡烛图"))
        self.chkBox_Caps.setText(_translate("MainWindow", "capsVisible"))
        self.chkBox_Outline.setText(_translate("MainWindow", "bodyOutlineVisible"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Y轴--QValueAxis"))
        self.label_5.setText(_translate("MainWindow", "最小值"))
        self.btnY_SetRange.setText(_translate("MainWindow", "设置范围"))
        self.label_6.setText(_translate("MainWindow", "最大值"))
        self.label_3.setText(_translate("MainWindow", "分度个数"))
        self.groupBox_4.setTitle(_translate("MainWindow", "X轴--QDateTimeAxis"))
        self.label_4.setText(_translate("MainWindow", "分度个数"))
        self.comboDateFormat.setItemText(0, _translate("MainWindow", "MM-dd"))
        self.comboDateFormat.setItemText(1, _translate("MainWindow", "M-d"))
        self.comboDateFormat.setItemText(2, _translate("MainWindow", "M月d日"))
        self.comboDateFormat.setItemText(3, _translate("MainWindow", "yyyy-MM-dd"))
        self.label_7.setText(_translate("MainWindow", "日期格式"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Setup), _translate("MainWindow", "图表设置"))
        self.actZoomReset.setText(_translate("MainWindow", "原始大小"))
        self.actZoomReset.setToolTip(_translate("MainWindow", "原始大小"))
        self.actQuit.setText(_translate("MainWindow", "退出"))
        self.actQuit.setToolTip(_translate("MainWindow", "退出"))
        self.actZoomIn.setText(_translate("MainWindow", "放大"))
        self.actZoomIn.setToolTip(_translate("MainWindow", "放大"))
        self.actZoomOut.setText(_translate("MainWindow", "缩小"))
        self.actZoomOut.setToolTip(_translate("MainWindow", "缩小"))
        self.actOpen.setText(_translate("MainWindow", "打开文件"))
        self.actOpen.setToolTip(_translate("MainWindow", "打开数据文件"))

from myChartView import QmyChartView
import res_rc
