# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(556, 364)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnClearText = QtWidgets.QPushButton(self.groupBox_4)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/212.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClearText.setIcon(icon)
        self.btnClearText.setObjectName("btnClearText")
        self.horizontalLayout.addWidget(self.btnClearText)
        self.btnClose = QtWidgets.QPushButton(self.groupBox_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon1)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.gridLayout_4.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnInputString = QtWidgets.QPushButton(self.groupBox_3)
        self.btnInputString.setObjectName("btnInputString")
        self.gridLayout_3.addWidget(self.btnInputString, 0, 0, 1, 1)
        self.btnInputInt = QtWidgets.QPushButton(self.groupBox_3)
        self.btnInputInt.setObjectName("btnInputInt")
        self.gridLayout_3.addWidget(self.btnInputInt, 0, 1, 1, 1)
        self.btnInputFloat = QtWidgets.QPushButton(self.groupBox_3)
        self.btnInputFloat.setObjectName("btnInputFloat")
        self.gridLayout_3.addWidget(self.btnInputFloat, 1, 0, 1, 1)
        self.btnInputItem = QtWidgets.QPushButton(self.groupBox_3)
        self.btnInputItem.setObjectName("btnInputItem")
        self.gridLayout_3.addWidget(self.btnInputItem, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnMsgQuestion = QtWidgets.QPushButton(self.groupBox_2)
        self.btnMsgQuestion.setObjectName("btnMsgQuestion")
        self.gridLayout_2.addWidget(self.btnMsgQuestion, 0, 0, 1, 1)
        self.btnMsgInformation = QtWidgets.QPushButton(self.groupBox_2)
        self.btnMsgInformation.setObjectName("btnMsgInformation")
        self.gridLayout_2.addWidget(self.btnMsgInformation, 0, 1, 1, 1)
        self.btnMsgWarning = QtWidgets.QPushButton(self.groupBox_2)
        self.btnMsgWarning.setObjectName("btnMsgWarning")
        self.gridLayout_2.addWidget(self.btnMsgWarning, 1, 0, 1, 1)
        self.btnMsgCritical = QtWidgets.QPushButton(self.groupBox_2)
        self.btnMsgCritical.setObjectName("btnMsgCritical")
        self.gridLayout_2.addWidget(self.btnMsgCritical, 1, 1, 1, 1)
        self.btnMsgAbout = QtWidgets.QPushButton(self.groupBox_2)
        self.btnMsgAbout.setObjectName("btnMsgAbout")
        self.gridLayout_2.addWidget(self.btnMsgAbout, 2, 0, 1, 1)
        self.btnMsgAboutQt = QtWidgets.QPushButton(self.groupBox_2)
        self.btnMsgAboutQt.setObjectName("btnMsgAboutQt")
        self.gridLayout_2.addWidget(self.btnMsgAboutQt, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(220, 0))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.btnSelDir = QtWidgets.QPushButton(self.groupBox)
        self.btnSelDir.setObjectName("btnSelDir")
        self.gridLayout.addWidget(self.btnSelDir, 1, 0, 1, 1)
        self.btnColor = QtWidgets.QPushButton(self.groupBox)
        self.btnColor.setObjectName("btnColor")
        self.gridLayout.addWidget(self.btnColor, 2, 0, 1, 1)
        self.btnOpen = QtWidgets.QPushButton(self.groupBox)
        self.btnOpen.setObjectName("btnOpen")
        self.gridLayout.addWidget(self.btnOpen, 0, 0, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.groupBox)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 1, 1, 1, 1)
        self.btnFont = QtWidgets.QPushButton(self.groupBox)
        self.btnFont.setObjectName("btnFont")
        self.gridLayout.addWidget(self.btnFont, 2, 1, 1, 1)
        self.btnOpenMulti = QtWidgets.QPushButton(self.groupBox)
        self.btnOpenMulti.setObjectName("btnOpenMulti")
        self.gridLayout.addWidget(self.btnOpenMulti, 0, 1, 1, 1)
        self.btnProgress = QtWidgets.QPushButton(self.groupBox)
        self.btnProgress.setObjectName("btnProgress")
        self.gridLayout.addWidget(self.btnProgress, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)

        self.retranslateUi(Dialog)
        self.btnClose.clicked.connect(Dialog.close)
        self.btnClearText.clicked.connect(self.plainTextEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btnOpen, self.btnOpenMulti)
        Dialog.setTabOrder(self.btnOpenMulti, self.btnSelDir)
        Dialog.setTabOrder(self.btnSelDir, self.btnSave)
        Dialog.setTabOrder(self.btnSave, self.btnColor)
        Dialog.setTabOrder(self.btnColor, self.btnFont)
        Dialog.setTabOrder(self.btnFont, self.btnMsgQuestion)
        Dialog.setTabOrder(self.btnMsgQuestion, self.btnMsgInformation)
        Dialog.setTabOrder(self.btnMsgInformation, self.btnInputString)
        Dialog.setTabOrder(self.btnInputString, self.btnInputInt)
        Dialog.setTabOrder(self.btnInputInt, self.btnInputFloat)
        Dialog.setTabOrder(self.btnInputFloat, self.btnInputItem)
        Dialog.setTabOrder(self.btnInputItem, self.btnClearText)
        Dialog.setTabOrder(self.btnClearText, self.plainTextEdit)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Demo6_1, 标准对话框的使用"))
        self.btnClearText.setText(_translate("Dialog", "清除文本框内容"))
        self.btnClose.setText(_translate("Dialog", "退出"))
        self.groupBox_3.setTitle(_translate("Dialog", "标准输入对话框 QInputDialog"))
        self.btnInputString.setText(_translate("Dialog", "输入字符串"))
        self.btnInputInt.setText(_translate("Dialog", "输入整数"))
        self.btnInputFloat.setText(_translate("Dialog", "输入浮点数"))
        self.btnInputItem.setText(_translate("Dialog", "条目选择输入"))
        self.groupBox_2.setTitle(_translate("Dialog", "标准消息框 QMessageBox"))
        self.btnMsgQuestion.setText(_translate("Dialog", "question"))
        self.btnMsgInformation.setText(_translate("Dialog", "information"))
        self.btnMsgWarning.setText(_translate("Dialog", "warning"))
        self.btnMsgCritical.setText(_translate("Dialog", "critical"))
        self.btnMsgAbout.setText(_translate("Dialog", "about"))
        self.btnMsgAboutQt.setText(_translate("Dialog", "aboutQt"))
        self.groupBox.setTitle(_translate("Dialog", "标准对话框"))
        self.btnSelDir.setText(_translate("Dialog", "选择已有目录"))
        self.btnColor.setText(_translate("Dialog", "选择颜色"))
        self.btnOpen.setText(_translate("Dialog", "打开一个文件"))
        self.btnSave.setText(_translate("Dialog", "保存文件"))
        self.btnFont.setText(_translate("Dialog", "选择字体"))
        self.btnOpenMulti.setText(_translate("Dialog", "打开多个文件"))
        self.btnProgress.setText(_translate("Dialog", "进度对话框"))

import res_rc
